
export type Pokemon = {
  dexNumber: string,
  name: string,
  berry: string,
  ingredient_1: string,
  ingredient_2: string,
  ingredient_3: string,
}

export const pokedex : Pokemon[] = [
  { dexNumber: "1", name: "Bulbasaur", berry: "Durin", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Potato",  },
  { dexNumber: "2", name: "Ivysaur", berry: "Durin", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Potato",  },
  { dexNumber: "3", name: "Venusaur", berry: "Durin", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Potato",  },
  { dexNumber: "4", name: "Charmander", berry: "Leppa", ingredient_1: "Sausage", ingredient_2: "Ginger", ingredient_3: "Herb",  },
  { dexNumber: "5", name: "Charmeleon", berry: "Leppa", ingredient_1: "Sausage", ingredient_2: "Ginger", ingredient_3: "Herb",  },
  { dexNumber: "6", name: "Charizard", berry: "Leppa", ingredient_1: "Sausage", ingredient_2: "Ginger", ingredient_3: "Herb",  },
  { dexNumber: "7", name: "Squirtle", berry: "Oran", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "8", name: "Wartortle", berry: "Oran", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "9", name: "Blastoise", berry: "Oran", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "10", name: "Caterpie", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Soybeans",  },
  { dexNumber: "11", name: "Metapod", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Soybeans",  },
  { dexNumber: "12", name: "Butterfree", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Soybeans",  },
  { dexNumber: "19", name: "Rattata", berry: "Persim", ingredient_1: "Apple", ingredient_2: "Soybeans", ingredient_3: "Sausage",  },
  { dexNumber: "20", name: "Raticate", berry: "Persim", ingredient_1: "Apple", ingredient_2: "Soybeans", ingredient_3: "Sausage",  },
  { dexNumber: "23", name: "Ekans", berry: "Chesto", ingredient_1: "Sausage", ingredient_2: "Egg", ingredient_3: "Herb",  },
  { dexNumber: "24", name: "Arbok", berry: "Chesto", ingredient_1: "Sausage", ingredient_2: "Egg", ingredient_3: "Herb",  },
  { dexNumber: "172", name: "Pichu", berry: "Grepa", ingredient_1: "Apple", ingredient_2: "Ginger", ingredient_3: "Egg",  },
  { dexNumber: "25", name: "Pikachu", berry: "Grepa", ingredient_1: "Apple", ingredient_2: "Ginger", ingredient_3: "Egg",  },
  { dexNumber: "26", name: "Raichu", berry: "Grepa", ingredient_1: "Apple", ingredient_2: "Ginger", ingredient_3: "Egg",  },
  { dexNumber: "173", name: "Cleffa", berry: "Pecha", ingredient_1: "Apple", ingredient_2: "Honey", ingredient_3: "Soybeans",  },
  { dexNumber: "35", name: "Clefairy", berry: "Pecha", ingredient_1: "Apple", ingredient_2: "Honey", ingredient_3: "Soybeans",  },
  { dexNumber: "36", name: "Clefable", berry: "Pecha", ingredient_1: "Apple", ingredient_2: "Honey", ingredient_3: "Soybeans",  },
  { dexNumber: "37", name: "Vulpix", berry: "Leppa", ingredient_1: "Soybeans", ingredient_2: "Corn", ingredient_3: "Potato",  },
  { dexNumber: "38", name: "Ninetails", berry: "Leppa", ingredient_1: "Soybeans", ingredient_2: "Corn", ingredient_3: "Potato",  },
  { dexNumber: "174", name: "Igglybuff", berry: "Pecha", ingredient_1: "Honey", ingredient_2: "Oil", ingredient_3: "Cacao",  },
  { dexNumber: "39", name: "Jigglypuff", berry: "Pecha", ingredient_1: "Honey", ingredient_2: "Oil", ingredient_3: "Cacao",  },
  { dexNumber: "40", name: "Wigglytuff", berry: "Pecha", ingredient_1: "Honey", ingredient_2: "Oil", ingredient_3: "Cacao",  },
  { dexNumber: "50", name: "Diglett", berry: "Figy", ingredient_1: "Tomato", ingredient_2: "Leek", ingredient_3: "Soybeans",  },
  { dexNumber: "51", name: "Dugtrio", berry: "Figy", ingredient_1: "Tomato", ingredient_2: "Leek", ingredient_3: "Soybeans",  },
  { dexNumber: "52", name: "Meowth", berry: "Persim", ingredient_1: "Milk", ingredient_2: "Sausage", ingredient_3: "0",  },
  { dexNumber: "53", name: "Persian", berry: "Persim", ingredient_1: "Milk", ingredient_2: "Sausage", ingredient_3: "0",  },
  { dexNumber: "54", name: "Psyduck", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Apple", ingredient_3: "Sausage",  },
  { dexNumber: "55", name: "Golduck", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Apple", ingredient_3: "Sausage",  },
  { dexNumber: "56", name: "Mankey", berry: "Cheri", ingredient_1: "Sausage", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "57", name: "Primeape", berry: "Cheri", ingredient_1: "Sausage", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "58", name: "Growlithe", berry: "Leppa", ingredient_1: "Herb", ingredient_2: "Sausage", ingredient_3: "Milk",  },
  { dexNumber: "59", name: "Arcanine", berry: "Leppa", ingredient_1: "Herb", ingredient_2: "Sausage", ingredient_3: "Milk",  },
  { dexNumber: "69", name: "Bellsprout", berry: "Durin", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "70", name: "Weepinbell", berry: "Durin", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "71", name: "Victreebel", berry: "Durin", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "74", name: "Geodude", berry: "Sitrus", ingredient_1: "Soybeans", ingredient_2: "Potato", ingredient_3: "Mushroom",  },
  { dexNumber: "75", name: "Graveler", berry: "Sitrus", ingredient_1: "Soybeans", ingredient_2: "Potato", ingredient_3: "Mushroom",  },
  { dexNumber: "76", name: "Golem", berry: "Sitrus", ingredient_1: "Soybeans", ingredient_2: "Potato", ingredient_3: "Mushroom",  },
  { dexNumber: "79", name: "Slowpoke", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Tail", ingredient_3: "Tomato",  },
  { dexNumber: "80", name: "Slowbro", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Tail", ingredient_3: "Tomato",  },
  { dexNumber: "199", name: "Slowking", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Tail", ingredient_3: "Tomato",  },
  { dexNumber: "81", name: "Magnemite", berry: "Belue", ingredient_1: "Oil", ingredient_2: "Herb", ingredient_3: "0",  },
  { dexNumber: "82", name: "Magneton", berry: "Belue", ingredient_1: "Oil", ingredient_2: "Herb", ingredient_3: "0",  },
  { dexNumber: "462", name: "Magnezone", berry: "Belue", ingredient_1: "Oil", ingredient_2: "Herb", ingredient_3: "0",  },
  { dexNumber: "84", name: "Doduo", berry: "Pamtre", ingredient_1: "Soybeans", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "85", name: "Dodrio", berry: "Pamtre", ingredient_1: "Soybeans", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "92", name: "Gastly", berry: "Bluk", ingredient_1: "Herb", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "93", name: "Haunter", berry: "Bluk", ingredient_1: "Herb", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "94", name: "Gengar", berry: "Bluk", ingredient_1: "Herb", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "95", name: "Onix", berry: "Sitrus", ingredient_1: "Tomato", ingredient_2: "Sausage", ingredient_3: "Potato",  },
  { dexNumber: "208", name: "Steelix", berry: "Belue", ingredient_1: "Tomato", ingredient_2: "Sausage", ingredient_3: "Potato",  },
  { dexNumber: "104", name: "Cubone", berry: "Figy", ingredient_1: "Ginger", ingredient_2: "Cacao", ingredient_3: "0",  },
  { dexNumber: "105", name: "Marowak", berry: "Figy", ingredient_1: "Ginger", ingredient_2: "Cacao", ingredient_3: "0",  },
  { dexNumber: "115", name: "Kangaskhan", berry: "Persim", ingredient_1: "Ginger", ingredient_2: "Potato", ingredient_3: "Soybeans",  },
  { dexNumber: "439", name: "Mime Jr.", berry: "Mago", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "122", name: "Mr. Mime", berry: "Mago", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "127", name: "Pinsir", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Apple", ingredient_3: "Sausage",  },
  { dexNumber: "132", name: "Ditto", berry: "Persim", ingredient_1: "Oil", ingredient_2: "Leek", ingredient_3: "Tail",  },
  { dexNumber: "133", name: "Eevee", berry: "Persim", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "134", name: "Vaporeon", berry: "Oran", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "135", name: "Jolteon", berry: "Grepa", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "136", name: "Flareon", berry: "Leppa", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "196", name: "Espeon", berry: "Mago", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "197", name: "Umbreon", berry: "Wiki", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "470", name: "Leafeon", berry: "Durin", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "471", name: "Glaceon", berry: "Rawst", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "700", name: "Sylveon", berry: "Pecha", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "147", name: "Dratini", berry: "Yache", ingredient_1: "Herb", ingredient_2: "Corn", ingredient_3: "Oil",  },
  { dexNumber: "148", name: "Dragonair", berry: "Yache", ingredient_1: "Herb", ingredient_2: "Corn", ingredient_3: "Oil",  },
  { dexNumber: "149", name: "Dragonite", berry: "Yache", ingredient_1: "Herb", ingredient_2: "Corn", ingredient_3: "Oil",  },
  { dexNumber: "152", name: "Chikorita", berry: "Durin", ingredient_1: "Cacao", ingredient_2: "Honey", ingredient_3: "Leek",  },
  { dexNumber: "153", name: "Bayleef", berry: "Durin", ingredient_1: "Cacao", ingredient_2: "Honey", ingredient_3: "Leek",  },
  { dexNumber: "154", name: "Meganium", berry: "Durin", ingredient_1: "Cacao", ingredient_2: "Honey", ingredient_3: "Leek",  },
  { dexNumber: "155", name: "Cyndaquil", berry: "Leppa", ingredient_1: "Ginger", ingredient_2: "Herb", ingredient_3: "Oil",  },
  { dexNumber: "156", name: "Quilava", berry: "Leppa", ingredient_1: "Ginger", ingredient_2: "Herb", ingredient_3: "Oil",  },
  { dexNumber: "157", name: "Typhlosion", berry: "Leppa", ingredient_1: "Ginger", ingredient_2: "Herb", ingredient_3: "Oil",  },
  { dexNumber: "158", name: "Totodile", berry: "Oran", ingredient_1: "Sausage", ingredient_2: "Oil", ingredient_3: "0",  },
  { dexNumber: "159", name: "Croconaw", berry: "Oran", ingredient_1: "Sausage", ingredient_2: "Oil", ingredient_3: "0",  },
  { dexNumber: "160", name: "Feraligatr", berry: "Oran", ingredient_1: "Sausage", ingredient_2: "Oil", ingredient_3: "0",  },
  { dexNumber: "175", name: "Togepi", berry: "Pecha", ingredient_1: "Egg", ingredient_2: "Ginger", ingredient_3: "Cacao",  },
  { dexNumber: "176", name: "Togetic", berry: "Pecha", ingredient_1: "Egg", ingredient_2: "Ginger", ingredient_3: "Cacao",  },
  { dexNumber: "468", name: "Togekiss", berry: "Pecha", ingredient_1: "Egg", ingredient_2: "Ginger", ingredient_3: "Cacao",  },
  { dexNumber: "179", name: "Mareep", berry: "Grepa", ingredient_1: "Herb", ingredient_2: "Egg", ingredient_3: "0",  },
  { dexNumber: "180", name: "Flaaffy", berry: "Grepa", ingredient_1: "Herb", ingredient_2: "Egg", ingredient_3: "0",  },
  { dexNumber: "181", name: "Ampharos", berry: "Grepa", ingredient_1: "Herb", ingredient_2: "Egg", ingredient_3: "0",  },
  { dexNumber: "438", name: "Bonsly", berry: "Sitrus", ingredient_1: "Tomato", ingredient_2: "Soybeans", ingredient_3: "Mushroom",  },
  { dexNumber: "185", name: "Sudowoodo", berry: "Sitrus", ingredient_1: "Tomato", ingredient_2: "Soybeans", ingredient_3: "Mushroom",  },
  { dexNumber: "194", name: "Wooper", berry: "Oran", ingredient_1: "Mushroom", ingredient_2: "Potato", ingredient_3: "Sausage",  },
  { dexNumber: "195", name: "Quagsire", berry: "Oran", ingredient_1: "Mushroom", ingredient_2: "Potato", ingredient_3: "Sausage",  },
  { dexNumber: "360", name: "Wynaut", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "202", name: "Wobbuffet", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "214", name: "Heracross", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Mushroom", ingredient_3: "Sausage",  },
  { dexNumber: "225", name: "Delibird", berry: "Pamtre", ingredient_1: "Egg", ingredient_2: "Apple", ingredient_3: "Cacao",  },
  { dexNumber: "228", name: "Houndour", berry: "Wiki", ingredient_1: "Herb", ingredient_2: "Ginger", ingredient_3: "Leek",  },
  { dexNumber: "229", name: "Houndoom", berry: "Wiki", ingredient_1: "Herb", ingredient_2: "Ginger", ingredient_3: "Leek",  },
  { dexNumber: "243", name: "Raiku", berry: "Grepa", ingredient_1: "Sausage", ingredient_2: "Herb", ingredient_3: "Leek",  },
  { dexNumber: "244", name: "Entei", berry: "Leppa", ingredient_1: "Oil", ingredient_2: "Tomato", ingredient_3: "Mushroom",  },
  { dexNumber: "245", name: "Suicune", berry: "Oran", ingredient_1: "Apple", ingredient_2: "Oil", ingredient_3: "Corn",  },
  { dexNumber: "246", name: "Larvitar", berry: "Sitrus", ingredient_1: "Ginger", ingredient_2: "Soybeans", ingredient_3: "Sausage",  },
  { dexNumber: "247", name: "Pupitar", berry: "Sitrus", ingredient_1: "Ginger", ingredient_2: "Soybeans", ingredient_3: "Sausage",  },
  { dexNumber: "248", name: "Tyranitar", berry: "Wiki", ingredient_1: "Ginger", ingredient_2: "Soybeans", ingredient_3: "Sausage",  },
  { dexNumber: "280", name: "Ralts", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Corn", ingredient_3: "Leek",  },
  { dexNumber: "281", name: "Kirlia", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Corn", ingredient_3: "Leek",  },
  { dexNumber: "282", name: "Gardevoir", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Corn", ingredient_3: "Leek",  },
  { dexNumber: "475", name: "Gallade", berry: "Cheri", ingredient_1: "Apple", ingredient_2: "Corn", ingredient_3: "Leek",  },
  { dexNumber: "287", name: "Slakoth", berry: "Persim", ingredient_1: "Tomato", ingredient_2: "Honey", ingredient_3: "Apple",  },
  { dexNumber: "288", name: "Vigoroth", berry: "Persim", ingredient_1: "Tomato", ingredient_2: "Honey", ingredient_3: "Apple",  },
  { dexNumber: "289", name: "Slaking", berry: "Persim", ingredient_1: "Tomato", ingredient_2: "Honey", ingredient_3: "Apple",  },
  { dexNumber: "304", name: "Aron", berry: "Belue", ingredient_1: "Sausage", ingredient_2: "Coffee", ingredient_3: "Soybeans",  },
  { dexNumber: "305", name: "Lairon", berry: "Belue", ingredient_1: "Sausage", ingredient_2: "Coffee", ingredient_3: "Soybeans",  },
  { dexNumber: "306", name: "Aggron", berry: "Belue", ingredient_1: "Sausage", ingredient_2: "Coffee", ingredient_3: "Soybeans",  },
  { dexNumber: "302", name: "Sableye", berry: "Wiki", ingredient_1: "Oil", ingredient_2: "Mushroom", ingredient_3: "Cacao",  },
  { dexNumber: "316", name: "Gulpin", berry: "Chesto", ingredient_1: "Soybeans", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "317", name: "Swalot", berry: "Chesto", ingredient_1: "Soybeans", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "333", name: "Swablu", berry: "Pamtre", ingredient_1: "Egg", ingredient_2: "Soybeans", ingredient_3: "Apple",  },
  { dexNumber: "334", name: "Altaria", berry: "Yache", ingredient_1: "Egg", ingredient_2: "Soybeans", ingredient_3: "Apple",  },
  { dexNumber: "353", name: "Shuppet", berry: "Bluk", ingredient_1: "Oil", ingredient_2: "Ginger", ingredient_3: "Mushroom",  },
  { dexNumber: "354", name: "Banette", berry: "Bluk", ingredient_1: "Oil", ingredient_2: "Ginger", ingredient_3: "Mushroom",  },
  { dexNumber: "359", name: "Absol", berry: "Wiki", ingredient_1: "Cacao", ingredient_2: "Apple", ingredient_3: "Mushroom",  },
  { dexNumber: "363", name: "Spheal", berry: "Rawst", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "Ginger",  },
  { dexNumber: "364", name: "Sealeo", berry: "Rawst", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "Ginger",  },
  { dexNumber: "365", name: "Walrein", berry: "Rawst", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "Ginger",  },
  { dexNumber: "403", name: "Shinx", berry: "Grepa", ingredient_1: "Tomato", ingredient_2: "Oil", ingredient_3: "Coffee",  },
  { dexNumber: "404", name: "Luxio", berry: "Grepa", ingredient_1: "Tomato", ingredient_2: "Oil", ingredient_3: "Coffee",  },
  { dexNumber: "405", name: "Luxray", berry: "Grepa", ingredient_1: "Tomato", ingredient_2: "Oil", ingredient_3: "Coffee",  },
  { dexNumber: "425", name: "Drifloon", berry: "Bluk", ingredient_1: "Corn", ingredient_2: "Oil", ingredient_3: "Potato",  },
  { dexNumber: "426", name: "Drifblim", berry: "Bluk", ingredient_1: "Corn", ingredient_2: "Oil", ingredient_3: "Potato",  },
  { dexNumber: "447", name: "Riolu", berry: "Cheri", ingredient_1: "Oil", ingredient_2: "Potato", ingredient_3: "Egg",  },
  { dexNumber: "448", name: "Lucario", berry: "Cheri", ingredient_1: "Oil", ingredient_2: "Potato", ingredient_3: "Egg",  },
  { dexNumber: "453", name: "Croagunk", berry: "Chesto", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "0",  },
  { dexNumber: "454", name: "Toxicroak", berry: "Chesto", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "0",  },
  { dexNumber: "459", name: "Snover", berry: "Rawst", ingredient_1: "Tomato", ingredient_2: "Egg", ingredient_3: "Mushroom",  },
  { dexNumber: "460", name: "Abomasnow", berry: "Rawst", ingredient_1: "Tomato", ingredient_2: "Egg", ingredient_3: "Mushroom",  },
  { dexNumber: "627", name: "Rufflet", berry: "Pamtre", ingredient_1: "Corn", ingredient_2: "Coffee", ingredient_3: "0",  },
  { dexNumber: "628", name: "Braviary", berry: "Pamtre", ingredient_1: "Corn", ingredient_2: "Coffee", ingredient_3: "0",  },
  { dexNumber: "702", name: "Dedenne", berry: "Grepa", ingredient_1: "Apple", ingredient_2: "Cacao", ingredient_3: "Corn",  },
  { dexNumber: "736", name: "Grubbin", berry: "Lum", ingredient_1: "Coffee", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "737", name: "Charjabug", berry: "Lum", ingredient_1: "Coffee", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "738", name: "Vikabolt", berry: "Lum", ingredient_1: "Coffee", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "759", name: "Stufful", berry: "Cheri", ingredient_1: "Corn", ingredient_2: "Sausage", ingredient_3: "Egg",  },
  { dexNumber: "760", name: "Bewear", berry: "Cheri", ingredient_1: "Corn", ingredient_2: "Sausage", ingredient_3: "Egg",  },
  { dexNumber: "764", name: "Comfey", berry: "Pecha", ingredient_1: "Corn", ingredient_2: "Ginger", ingredient_3: "Cacao",  },
  { dexNumber: "778", name: "Mimikyu", berry: "Bluk", ingredient_1: "Apple", ingredient_2: "Coffee", ingredient_3: "Mushroom",  },
  { dexNumber: "845", name: "Cramorant", berry: "Pamtre", ingredient_1: "Oil", ingredient_2: "Potato", ingredient_3: "Egg",  },
  { dexNumber: "906", name: "Sprigatito", berry: "Durin", ingredient_1: "Potato", ingredient_2: "Milk", ingredient_3: "Ginger",  },
  { dexNumber: "907", name: "Floragato", berry: "Durin", ingredient_1: "Potato", ingredient_2: "Milk", ingredient_3: "Ginger",  },
  { dexNumber: "908", name: "Meowscarada", berry: "Wiki", ingredient_1: "Potato", ingredient_2: "Milk", ingredient_3: "Ginger",  },
  { dexNumber: "909", name: "Fuecoco", berry: "Leppa", ingredient_1: "Apple", ingredient_2: "Sausage", ingredient_3: "Herb",  },
  { dexNumber: "910", name: "Crocalor", berry: "Leppa", ingredient_1: "Apple", ingredient_2: "Sausage", ingredient_3: "Herb",  },
  { dexNumber: "911", name: "Skeledirge", berry: "Bluk", ingredient_1: "Apple", ingredient_2: "Sausage", ingredient_3: "Herb",  },
  { dexNumber: "912", name: "Quaxly", berry: "Oran", ingredient_1: "Soybeans", ingredient_2: "Leek", ingredient_3: "Oil",  },
  { dexNumber: "913", name: "Quaxwell", berry: "Oran", ingredient_1: "Soybeans", ingredient_2: "Leek", ingredient_3: "Oil",  },
  { dexNumber: "914", name: "Quaquaval", berry: "Cheri", ingredient_1: "Soybeans", ingredient_2: "Leek", ingredient_3: "Oil",  },
]

export const typeDivergentPokedex : string[] = [
  "Venusaur",
  "Charizard",
  "Blastoise",
  "Butterfree",
  "Raticate",
  "Arbok",
  "Raichu",
  "Clefable",
  "Ninetails",
  "Wigglytuff",
  "Dugtrio",
  "Persian",
  "Golduck",
  "Primeape",
  "Arcanine",
  "Victreebel",
  "Golem",
  "Slowbro",
  "Slowking",
  "Magnezone",
  "Dodrio",
  "Gengar",
  "Onix",
  "Steelix",
  "Marowak",
  "Kangaskhan",
  "Mr. Mime",
  "Pinsir",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Espeon",
  "Umbreon",
  "Leafeon",
  "Glaceon",
  "Sylveon",
  "Dragonite",
  "Meganium",
  "Typhlosion",
  "Feraligatr",
  "Togekiss",
  "Ampharos",
  "Sudowoodo",
  "Quagsire",
  "Wobbuffet",
  "Heracross",
  "Delibird",
  "Houndoom",
  "Raiku",
  "Entei",
  "Suicune",
  "Larvitar",
  "Tyranitar",
  "Gardevoir",
  "Gallade",
  "Slaking",
  "Sableye",
  "Gulpin",
  "Swalot",
  "Swablu",
  "Altaria",
  "Banette",
  "Absol",
  "Spheal",
  "Walrein",
  "Riolu",
  "Lucario",
  "Croagunk",
  "Toxicroak",
  "Abomasnow",
  "Dedenne",
  "Bewear",
  "Comfey",
  "Cramorant",
  "Sprigatito",
  "Meowscarada",
  "Fuecoco",
  "Skeledirge",
  "Quaxly",
  "Quaquaval",
  "Aggron",
  "Luxray",
  "Vikabolt",
]

export type BoxEntry = {
  DexNumber: string,
  Perf?: boolean,
  ingredientLevel30?: boolean,
  ingredientLevel60?: boolean,
  Pokemon: string,
}

export enum IngredientLevel {
  Lvl0,
  Lvl30,
  Lvl60
}

export enum CacheState {
  Selected = 1, // 001
  IngLvl30 = 2, // 010
  IngLvl60 = 4, // 100
}

export const pokemonBox : BoxEntry[] = [
  { DexNumber: "1", Pokemon: "Bulbasaur",  },
  { DexNumber: "2", Pokemon: "Ivysaur",  },
  { DexNumber: "3", Pokemon: "Venusaur",  },
  { DexNumber: "4", Pokemon: "Charmander",  },
  { DexNumber: "5", Pokemon: "Charmeleon",  },
  { DexNumber: "6", Pokemon: "Charizard",  },
  { DexNumber: "7", Pokemon: "Squirtle",  },
  { DexNumber: "8", Pokemon: "Wartortle",  },
  { DexNumber: "9", Pokemon: "Blastoise",  },
  { DexNumber: "10", Pokemon: "Caterpie",  },
  { DexNumber: "11", Pokemon: "Metapod",  },
  { DexNumber: "12", Pokemon: "Butterfree",  },
  { DexNumber: "19", Pokemon: "Rattata",  },
  { DexNumber: "20", Pokemon: "Raticate",  },
  { DexNumber: "23", Pokemon: "Ekans",  },
  { DexNumber: "24", Pokemon: "Arbok",  },
  { DexNumber: "172", Pokemon: "Pichu",  },
  { DexNumber: "25", Pokemon: "Pikachu",  },
  { DexNumber: "26", Pokemon: "Raichu",  },
  { DexNumber: "173", Pokemon: "Cleffa",  },
  { DexNumber: "35", Pokemon: "Clefairy",  },
  { DexNumber: "36", Pokemon: "Clefable",  },
  { DexNumber: "37", Pokemon: "Vulpix",  },
  { DexNumber: "38", Pokemon: "Ninetails",  },
  { DexNumber: "174", Pokemon: "Igglybuff",  },
  { DexNumber: "39", Pokemon: "Jigglypuff",  },
  { DexNumber: "40", Pokemon: "Wigglytuff",  },
  { DexNumber: "50", Pokemon: "Diglett",  },
  { DexNumber: "51", Pokemon: "Dugtrio",  },
  { DexNumber: "52", Pokemon: "Meowth",  },
  { DexNumber: "53", Pokemon: "Persian",  },
  { DexNumber: "54", Pokemon: "Psyduck",  },
  { DexNumber: "55", Pokemon: "Golduck",  },
  { DexNumber: "56", Pokemon: "Mankey",  },
  { DexNumber: "57", Pokemon: "Primeape",  },
  { DexNumber: "58", Pokemon: "Growlithe",  },
  { DexNumber: "59", Pokemon: "Arcanine",  },
  { DexNumber: "69", Pokemon: "Bellsprout",  },
  { DexNumber: "70", Pokemon: "Weepinbell",  },
  { DexNumber: "71", Pokemon: "Victreebel",  },
  { DexNumber: "74", Pokemon: "Geodude",  },
  { DexNumber: "75", Pokemon: "Graveler",  },
  { DexNumber: "76", Pokemon: "Golem",  },
  { DexNumber: "79", Pokemon: "Slowpoke",  },
  { DexNumber: "80", Pokemon: "Slowbro",  },
  { DexNumber: "199", Pokemon: "Slowking",  },
  { DexNumber: "81", Pokemon: "Magnemite",  },
  { DexNumber: "82", Pokemon: "Magneton",  },
  { DexNumber: "462", Pokemon: "Magnezone",  },
  { DexNumber: "84", Pokemon: "Doduo",  },
  { DexNumber: "85", Pokemon: "Dodrio",  },
  { DexNumber: "92", Pokemon: "Gastly",  },
  { DexNumber: "93", Pokemon: "Haunter",  },
  { DexNumber: "94", Pokemon: "Gengar",  },
  { DexNumber: "95", Pokemon: "Onix",  },
  { DexNumber: "208", Pokemon: "Steelix",  },
  { DexNumber: "104", Pokemon: "Cubone",  },
  { DexNumber: "105", Pokemon: "Marowak",  },
  { DexNumber: "115", Pokemon: "Kangaskhan",  },
  { DexNumber: "439", Pokemon: "Mime Jr.",  },
  { DexNumber: "122", Pokemon: "Mr. Mime",  },
  { DexNumber: "127", Pokemon: "Pinsir",  },
  { DexNumber: "132", Pokemon: "Ditto",  },
  { DexNumber: "133", Pokemon: "Eevee",  },
  { DexNumber: "134", Pokemon: "Vaporeon",  },
  { DexNumber: "135", Pokemon: "Jolteon",  },
  { DexNumber: "136", Pokemon: "Flareon",  },
  { DexNumber: "196", Pokemon: "Espeon",  },
  { DexNumber: "197", Pokemon: "Umbreon",  },
  { DexNumber: "470", Pokemon: "Leafeon",  },
  { DexNumber: "471", Pokemon: "Glaceon",  },
  { DexNumber: "700", Pokemon: "Sylveon",  },
  { DexNumber: "147", Pokemon: "Dratini",  },
  { DexNumber: "148", Pokemon: "Dragonair",  },
  { DexNumber: "149", Pokemon: "Dragonite",  },
  { DexNumber: "152", Pokemon: "Chikorita",  },
  { DexNumber: "153", Pokemon: "Bayleef",  },
  { DexNumber: "154", Pokemon: "Meganium",  },
  { DexNumber: "155", Pokemon: "Cyndaquil",  },
  { DexNumber: "156", Pokemon: "Quilava",  },
  { DexNumber: "157", Pokemon: "Typhlosion",  },
  { DexNumber: "158", Pokemon: "Totodile",  },
  { DexNumber: "159", Pokemon: "Croconaw",  },
  { DexNumber: "160", Pokemon: "Feraligatr",  },
  { DexNumber: "175", Pokemon: "Togepi",  },
  { DexNumber: "176", Pokemon: "Togetic",  },
  { DexNumber: "468", Pokemon: "Togekiss",  },
  { DexNumber: "179", Pokemon: "Mareep",  },
  { DexNumber: "180", Pokemon: "Flaaffy",  },
  { DexNumber: "181", Pokemon: "Ampharos",  },
  { DexNumber: "438", Pokemon: "Bonsly",  },
  { DexNumber: "185", Pokemon: "Sudowoodo",  },
  { DexNumber: "194", Pokemon: "Wooper",  },
  { DexNumber: "195", Pokemon: "Quagsire",  },
  { DexNumber: "360", Pokemon: "Wynaut",  },
  { DexNumber: "202", Pokemon: "Wobbuffet",  },
  { DexNumber: "214", Pokemon: "Heracross",  },
  { DexNumber: "225", Pokemon: "Delibird",  },
  { DexNumber: "228", Pokemon: "Houndour",  },
  { DexNumber: "229", Pokemon: "Houndoom",  },
  { DexNumber: "243", Pokemon: "Raiku",  },
  { DexNumber: "244", Pokemon: "Entei",  },
  { DexNumber: "245", Pokemon: "Suicune",  },
  { DexNumber: "246", Pokemon: "Larvitar",  },
  { DexNumber: "247", Pokemon: "Pupitar",  },
  { DexNumber: "248", Pokemon: "Tyranitar",  },
  { DexNumber: "280", Pokemon: "Ralts",  },
  { DexNumber: "281", Pokemon: "Kirlia",  },
  { DexNumber: "282", Pokemon: "Gardevoir",  },
  { DexNumber: "475", Pokemon: "Gallade",  },
  { DexNumber: "287", Pokemon: "Slakoth",  },
  { DexNumber: "288", Pokemon: "Vigoroth",  },
  { DexNumber: "289", Pokemon: "Slaking",  },
  { DexNumber: "304", Pokemon: "Aron",  },
  { DexNumber: "305", Pokemon: "Lairon",  },
  { DexNumber: "306", Pokemon: "Aggron",  },
  { DexNumber: "302", Pokemon: "Sableye",  },
  { DexNumber: "316", Pokemon: "Gulpin",  },
  { DexNumber: "317", Pokemon: "Swalot",  },
  { DexNumber: "333", Pokemon: "Swablu",  },
  { DexNumber: "334", Pokemon: "Altaria",  },
  { DexNumber: "353", Pokemon: "Shuppet",  },
  { DexNumber: "354", Pokemon: "Banette",  },
  { DexNumber: "359", Pokemon: "Absol",  },
  { DexNumber: "363", Pokemon: "Spheal",  },
  { DexNumber: "364", Pokemon: "Sealeo",  },
  { DexNumber: "365", Pokemon: "Walrein",  },
  { DexNumber: "403", Pokemon: "Shinx",  },
  { DexNumber: "404", Pokemon: "Luxio",  },
  { DexNumber: "405", Pokemon: "Luxray",  },
  { DexNumber: "425", Pokemon: "Drifloon",  },
  { DexNumber: "426", Pokemon: "Drifblim",  },
  { DexNumber: "447", Pokemon: "Riolu",  },
  { DexNumber: "448", Pokemon: "Lucario",  },
  { DexNumber: "453", Pokemon: "Croagunk",  },
  { DexNumber: "454", Pokemon: "Toxicroak",  },
  { DexNumber: "459", Pokemon: "Snover",  },
  { DexNumber: "460", Pokemon: "Abomasnow",  },
  { DexNumber: "627", Pokemon: "Rufflet",  },
  { DexNumber: "628", Pokemon: "Braviary",  },
  { DexNumber: "702", Pokemon: "Dedenne",  },
  { DexNumber: "736", Pokemon: "Grubbin",  },
  { DexNumber: "737", Pokemon: "Charjabug",  },
  { DexNumber: "738", Pokemon: "Vikabolt",  },
  { DexNumber: "759", Pokemon: "Stufful",  },
  { DexNumber: "760", Pokemon: "Bewear",  },
  { DexNumber: "764", Pokemon: "Comfey",  },
  { DexNumber: "778", Pokemon: "Mimikyu",  },
  { DexNumber: "845", Pokemon: "Cramorant",  },
  { DexNumber: "906", Pokemon: "Sprigatito",  },
  { DexNumber: "907", Pokemon: "Floragato",  },
  { DexNumber: "908", Pokemon: "Meowscarada",  },
  { DexNumber: "909", Pokemon: "Fuecoco",  },
  { DexNumber: "910", Pokemon: "Crocalor",  },
  { DexNumber: "911", Pokemon: "Skeledirge",  },
  { DexNumber: "912", Pokemon: "Quaxly",  },
  { DexNumber: "913", Pokemon: "Quaxwell",  },
  { DexNumber: "914", Pokemon: "Quaquaval",  },
]

export type BerryTypes = {
  index: string,
  berryName: string,
  berryImageUri: string,
  typeName: string,
  typeImageUri: string,
}

export const berryTypes : BerryTypes[] = [
  // { index: '0', berryName: "-", typeName: "-", berryImageUri: "close-button.png", typeImageUri: "close-button.png" },
  { index: '1', berryName: "Persim", typeName: "Normal", berryImageUri: "./berries/persimberry.png", typeImageUri: "./types/normal.png" },
  { index: '2', berryName: "Leppa", typeName: "Fire", berryImageUri: "./berries/leppaberry.png", typeImageUri: "./types/fire.png" },
  { index: '3', berryName: "Oran", typeName: "Water", berryImageUri: "./berries/oranberry.png", typeImageUri: "./types/water.png" },
  { index: '4', berryName: "Grepa", typeName: "Electric", berryImageUri: "./berries/grepaberry.png", typeImageUri: "./types/electric.png" },
  { index: '5', berryName: "Durin", typeName: "Grass", berryImageUri: "./berries/durinberry.png", typeImageUri: "./types/grass.png" },
  { index: '6', berryName: "Rawst", typeName: "Ice", berryImageUri: "./berries/rawstberry.png", typeImageUri: "./types/ice.png" },
  { index: '7', berryName: "Cheri", typeName: "Fighting", berryImageUri: "./berries/cheriberry.png", typeImageUri: "./types/fighting.png" },
  { index: '8', berryName: "Chesto", typeName: "Poison", berryImageUri: "./berries/chestoberry.png", typeImageUri: "./types/poison.png" },
  { index: '9', berryName: "Figy", typeName: "Ground", berryImageUri: "./berries/figyberry.png", typeImageUri: "./types/ground.png" },
  { index: '10', berryName: "Pamtre", typeName: "Flying", berryImageUri: "./berries/pamtreberry.png", typeImageUri: "./types/flying.png" },
  { index: '11', berryName: "Mago", typeName: "Psychic", berryImageUri: "./berries/magoberry.png", typeImageUri: "./types/psychic.png" },
  { index: '12', berryName: "Lum", typeName: "Bug", berryImageUri: "./berries/lumberry.png", typeImageUri: "./types/bug.png" },
  { index: '13', berryName: "Sitrus", typeName: "Rock", berryImageUri: "./berries/sitrusberry.png", typeImageUri: "./types/rock.png" },
  { index: '14', berryName: "Bluk", typeName: "Ghost", berryImageUri: "./berries/blukberry.png", typeImageUri: "./types/ghost.png" },
  { index: '15', berryName: "Yache", typeName: "Dragon", berryImageUri: "./berries/yacheberry.png", typeImageUri: "./types/dragon.png" },
  { index: '16', berryName: "Wiki", typeName: "Dark", berryImageUri: "./berries/wikiberry.png", typeImageUri: "./types/dark.png" },
  { index: '17', berryName: "Belue", typeName: "Steel", berryImageUri: "./berries/belueberry.png", typeImageUri: "./types/steel.png" },
  { index: '18', berryName: "Pecha", typeName: "Fairy", berryImageUri: "./berries/pechaberry.png", typeImageUri: "./types/fairy.png" },
]

export type Recipe = {
  key: string,
  Type: string,
  Recipe: string,
  Apple: string,
  Honey: string,
  Milk: string,
  Ginger: string,
  Oil: string,
  Cacao: string,
  Egg: string,
  Soybeans: string,
  Potato: string,
  Tomato: string,
  Mushroom: string,
  Tail: string,
  Herb: string,
  Leek: string,
  Corn: string,
  Sausage: string,
  Coffee?: string,
  Total_ingredients: string,
}

export const enum RecipePossibility {
    Possible,
    Impossible,
    Other
}

export type Ingredients = {
  name: string,
  uri?: string | undefined,
}

export const ingredients: Ingredients[] = [
  {name: "Apple", uri: "./ingredients/fancyapple.png"},
  {name: "Honey", uri: "./ingredients/honey.png"},
  {name: "Milk", uri: "./ingredients/moomoomilk.png"},
  {name: "Ginger", uri: "./ingredients/warmingginger.png"},
  {name: "Oil", uri: "./ingredients/pureoil.png"},
  {name: "Cacao", uri: "./ingredients/soothingcacao.png"},
  {name: "Egg", uri: "./ingredients/fancyegg.png"},
  {name: "Soybeans", uri: "./ingredients/greengrasssoybeans.png"},
  {name: "Potato", uri: "./ingredients/softpotato.png"},
  {name: "Tomato", uri: "./ingredients/snoozytomato.png"},
  {name: "Mushroom", uri: "./ingredients/tastymushroom.png"},
  {name: "Tail", uri: "./ingredients/slowpoketail.png"},
  {name: "Herb", uri: "./ingredients/fieryherb.png"},
  {name: "Leek", uri: "./ingredients/largeleek.png"},
  {name: "Corn", uri: "./ingredients/greengrasscorn.png"},
  {name: "Sausage", uri: "./ingredients/beansausage.png"},
  {name: "Coffee", uri: "./ingredients/rousingcoffee.png"},
]

export const recipeTypes = [
    "Curries/Stews",
    "Salads",
    "Desserts/Drinks",
]

export const recipes : Recipe[] = [
  { key: '0', Type: "Curries/Stews", Recipe: "Fancy Apple Curry", Apple: "7", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '1', Type: "Curries/Stews", Recipe: "Simple Chowder", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '2', Type: "Curries/Stews", Recipe: "Beanburger Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "7", Total_ingredients: "7",  },
  { key: '3', Type: "Curries/Stews", Recipe: "Mild Honey Curry", Apple: "0", Honey: "7", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '4', Type: "Curries/Stews", Recipe: "Solar Power Tomato Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "10", Mushroom: "0", Tail: "0", Herb: "5", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '5', Type: "Curries/Stews", Recipe: "Drought Katsu Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "10", Total_ingredients: "15",  },
  { key: '6', Type: "Curries/Stews", Recipe: "Hearty Cheeseburger Curry", Apple: "0", Honey: "0", Milk: "8", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "8", Total_ingredients: "16",  },
  { key: '7', Type: "Curries/Stews", Recipe: "Melty Omelette Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "10", Soybeans: "0", Potato: "0", Tomato: "6", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '8', Type: "Curries/Stews", Recipe: "Soft Potato Chowder", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "8", Tomato: "0", Mushroom: "4", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "22",  },
  { key: '9', Type: "Curries/Stews", Recipe: "Spore Mushroom Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "0", Mushroom: "14", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '10', Type: "Curries/Stews", Recipe: "Bulk Up Bean Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "4", Soybeans: "12", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "4", Leek: "0", Corn: "0", Sausage: "6", Total_ingredients: "26",  },
  { key: '11', Type: "Curries/Stews", Recipe: "Limber Corn Stew", Apple: "0", Honey: "0", Milk: "8", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "8", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "14", Sausage: "0", Total_ingredients: "30",  },
  { key: '12', Type: "Curries/Stews", Recipe: "Spicy Leek Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "10", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "8", Leek: "14", Corn: "0", Sausage: "0", Total_ingredients: "32",  },
  { key: '13', Type: "Curries/Stews", Recipe: "Grilled Tail Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "8", Herb: "25", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "33",  },
  { key: '14', Type: "Curries/Stews", Recipe: "Egg Bomb Curry", Apple: "11", Honey: "12", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "8", Soybeans: "0", Potato: "4", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '15', Type: "Curries/Stews", Recipe: "Ninja Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "24", Potato: "0", Tomato: "0", Mushroom: "5", Tail: "0", Herb: "0", Leek: "12", Corn: "0", Sausage: "9", Total_ingredients: "50",  },
  { key: '16', Type: "Curries/Stews", Recipe: "Dream Eater Butter Curry", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "12", Egg: "0", Soybeans: "0", Potato: "18", Tomato: "15", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "55",  },
  { key: '17', Type: "Curries/Stews", Recipe: "Inferno Corn Keema Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "12", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "27", Leek: "0", Corn: "14", Sausage: "24", Total_ingredients: "77",  },
  { key: '18', Type: "Salads", Recipe: "Bean Ham Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "8", Total_ingredients: "8",  },
  { key: '19', Type: "Salads", Recipe: "Snoozy Tomato Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '20', Type: "Salads", Recipe: "Fancy Apple Salad", Apple: "8", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '21', Type: "Salads", Recipe: "Immunity Leek Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "5", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "10", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '22', Type: "Salads", Recipe: "Snow Cloak Caesar Salad", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "6", Total_ingredients: "16",  },
  { key: '23', Type: "Salads", Recipe: "Water Veil Tofu Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "15", Potato: "0", Tomato: "9", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "24",  },
  { key: '24', Type: "Salads", Recipe: "Heat Wave Tofu Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "10", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "6", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '25', Type: "Salads", Recipe: "Fury Attack Corn Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "8", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "9", Sausage: "0", Total_ingredients: "17",  },
  { key: '26', Type: "Salads", Recipe: "Superpower Extreme Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "6", Oil: "0", Cacao: "0", Egg: "5", Soybeans: "0", Potato: "3", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "9", Total_ingredients: "23",  },
  { key: '27', Type: "Salads", Recipe: "Moomoo Caprese Salad", Apple: "0", Honey: "0", Milk: "12", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "6", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '28', Type: "Salads", Recipe: "Contrary Chocolate Meat Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "14", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "9", Total_ingredients: "23",  },
  { key: '29', Type: "Salads", Recipe: "Dazzling Apple Cheese Salad", Apple: "15", Honey: "0", Milk: "5", Ginger: "0", Oil: "3", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '30', Type: "Salads", Recipe: "Slowpoke Tail Pepper Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "10", Herb: "10", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "25",  },
  { key: '31', Type: "Salads", Recipe: "Spore Mushroom Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "8", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "17", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "33",  },
  { key: '32', Type: "Salads", Recipe: "Overheat Ginger Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "10", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "0", Tail: "0", Herb: "17", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '33', Type: "Salads", Recipe: "Gluttony Potato Salad", Apple: "6", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "9", Soybeans: "0", Potato: "14", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "7", Total_ingredients: "36",  },
  { key: '34', Type: "Salads", Recipe: "Calm Mind Fruit Salad", Apple: "21", Honey: "16", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "12", Sausage: "0", Total_ingredients: "49",  },
  { key: '35', Type: "Salads", Recipe: "Ninja Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "11", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "19", Potato: "0", Tomato: "0", Mushroom: "12", Tail: "0", Herb: "0", Leek: "15", Corn: "0", Sausage: "0", Total_ingredients: "57",  },
  { key: '36', Type: "Salads", Recipe: "Greengrass Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "22", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "14", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "17", Sausage: "0", Total_ingredients: "62",  },
  { key: '37', Type: "Desserts/Drinks", Recipe: "Warm Moomoo Milk", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '38', Type: "Desserts/Drinks", Recipe: "Fancy Apple Juice", Apple: "8", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '39', Type: "Desserts/Drinks", Recipe: "Craft Soda Pop", Apple: "0", Honey: "9", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "9",  },
  { key: '40', Type: "Desserts/Drinks", Recipe: "Fluffy Sweet Potatoes", Apple: "0", Honey: "0", Milk: "5", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "14",  },
  { key: '41', Type: "Desserts/Drinks", Recipe: "Cloud Nine Soy Cake", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "8", Soybeans: "7", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '42', Type: "Desserts/Drinks", Recipe: "Ember Ginger Tea", Apple: "7", Honey: "0", Milk: "0", Ginger: "9", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '43', Type: "Desserts/Drinks", Recipe: "Lucky Chant Apple Pie", Apple: "12", Honey: "0", Milk: "4", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '44', Type: "Desserts/Drinks", Recipe: "Stalwart Vegetable Juice", Apple: "7", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "9", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '45', Type: "Desserts/Drinks", Recipe: "Huge Power Soy Donuts", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "12", Cacao: "7", Egg: "0", Soybeans: "16", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '46', Type: "Desserts/Drinks", Recipe: "Petal Dance Chocolate Tart", Apple: "11", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "11", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "22",  },
  { key: '47', Type: "Desserts/Drinks", Recipe: "Hustle Protein Smoothie", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "15", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '48', Type: "Desserts/Drinks", Recipe: "Big Malasada", Apple: "0", Honey: "6", Milk: "7", Ginger: "0", Oil: "10", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '49', Type: "Desserts/Drinks", Recipe: "Sweet Scent Chocolate Cake", Apple: "0", Honey: "9", Milk: "7", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "24",  },
  { key: '50', Type: "Desserts/Drinks", Recipe: "Steadfast Ginger Cookies", Apple: "0", Honey: "14", Milk: "0", Ginger: "12", Oil: "0", Cacao: "5", Egg: "4", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '51', Type: "Desserts/Drinks", Recipe: "Lovely Kiss Smoothie", Apple: "11", Honey: "7", Milk: "9", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '52', Type: "Desserts/Drinks", Recipe: "Neroli's Restorative Tea", Apple: "15", Honey: "0", Milk: "0", Ginger: "11", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "9", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '53', Type: "Desserts/Drinks", Recipe: "Explosion Popcorn", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "14", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "15", Sausage: "0", Total_ingredients: "36",  },
  { key: '54', Type: "Desserts/Drinks", Recipe: "Jigglypuff's Fruity Flan", Apple: "10", Honey: "20", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "15", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "55",  },
  { key: '55', Type: "Desserts/Drinks", Recipe: "Teatime Corn Scones", Apple: "20", Honey: "0", Milk: "9", Ginger: "20", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "18", Sausage: "0", Total_ingredients: "67",  },
  { key: '56', Type: "Desserts/Drinks", Recipe: "Flower Gift Macarons", Apple: "0", Honey: "17", Milk: "10", Ginger: "0", Oil: "0", Cacao: "25", Egg: "25", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "77",  },
  { key: '57', Type: "Curries/Stews", Recipe: "Dizzy Punch Spicy Curry", Apple: "0", Honey: "11", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "11", Leek: "0", Corn: "0", Sausage: "0", Coffee: "11", Total_ingredients: "33",  },
  { key: '58', Type: "Curries/Stews", Recipe: "Hidden Power Perk-Up Stew", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "28", Potato: "0", Tomato: "25", Mushroom: "23", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Coffee: "16", Total_ingredients: "?",  },
  { key: '59', Type: "Salads", Recipe: "Defiant Coffee-Dressed Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "22", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "22", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "28", Coffee: "28", Total_ingredients: "?",  },
  { key: '60', Type: "Salads", Recipe: "Cross Chop Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "20", Soybeans: "0", Potato: "0", Tomato: "10", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "11", Sausage: "15", Coffee: "0", Total_ingredients: "?",  },
  { key: '61', Type: "Desserts/Drinks", Recipe: "Early Bird Coffee Jelly", Apple: "0", Honey: "12", Milk: "14", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Coffee: "16", Total_ingredients: "?",  },
  { key: '62', Type: "Desserts/Drinks", Recipe: "Zing Zap Spiced Cola", Apple: "35", Honey: "0", Milk: "0", Ginger: "20", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "20", Corn: "0", Sausage: "0", Coffee: "12", Total_ingredients: "?",  },
]

export type TypeGroup = {
  key: string,
  pokemon: string[],
  default: string,
  berry: string,
}

export const typeGroups : TypeGroup[] = [
  { key: "Bulbasaur_Durin", pokemon: [ "Bulbasaur", "Ivysaur", "Venusaur",  ], default: "Venusaur", berry: "Durin",  },
  { key: "Charmander_Leppa", pokemon: [ "Charmander", "Charmeleon", "Charizard",  ], default: "Charizard", berry: "Leppa",  },
  { key: "Squirtle_Oran", pokemon: [ "Squirtle", "Wartortle", "Blastoise",  ], default: "Blastoise", berry: "Oran",  },
  { key: "Caterpie_Lum", pokemon: [ "Caterpie", "Metapod", "Butterfree",  ], default: "Butterfree", berry: "Lum",  },
  { key: "Rattata_Persim", pokemon: [ "Rattata", "Raticate",  ], default: "Raticate", berry: "Persim",  },
  { key: "Ekans_Chesto", pokemon: [ "Ekans", "Arbok",  ], default: "Arbok", berry: "Chesto",  },
  { key: "Pichu_Grepa", pokemon: [ "Pichu", "Pikachu", "Raichu",  ], default: "Raichu", berry: "Grepa",  },
  { key: "Cleffa_Pecha", pokemon: [ "Cleffa", "Clefairy", "Clefable",  ], default: "Clefable", berry: "Pecha",  },
  { key: "Vulpix_Leppa", pokemon: [ "Vulpix", "Ninetails",  ], default: "Ninetails", berry: "Leppa",  },
  { key: "Igglybuff_Pecha", pokemon: [ "Igglybuff", "Jigglypuff", "Wigglytuff",  ], default: "Wigglytuff", berry: "Pecha",  },
  { key: "Diglett_Figy", pokemon: [ "Diglett", "Dugtrio",  ], default: "Dugtrio", berry: "Figy",  },
  { key: "Meowth_Persim", pokemon: [ "Meowth", "Persian",  ], default: "Persian", berry: "Persim",  },
  { key: "Psyduck_Oran", pokemon: [ "Psyduck", "Golduck",  ], default: "Golduck", berry: "Oran",  },
  { key: "Mankey_Cheri", pokemon: [ "Mankey", "Primeape",  ], default: "Primeape", berry: "Cheri",  },
  { key: "Growlithe_Leppa", pokemon: [ "Growlithe", "Arcanine",  ], default: "Arcanine", berry: "Leppa",  },
  { key: "Bellsprout_Durin", pokemon: [ "Bellsprout", "Weepinbell", "Victreebel",  ], default: "Victreebel", berry: "Durin",  },
  { key: "Geodude_Sitrus", pokemon: [ "Geodude", "Graveler", "Golem",  ], default: "Golem", berry: "Sitrus",  },
  { key: "Slowpoke_Oran", pokemon: [ "Slowpoke", "Slowbro", "Slowking",  ], default: "Slowpoke", berry: "Oran",  },
  { key: "Magnemite_Belue", pokemon: [ "Magnemite", "Magneton", "Magnezone",  ], default: "Magnezone", berry: "Belue",  },
  { key: "Doduo_Pamtre", pokemon: [ "Doduo", "Dodrio",  ], default: "Dodrio", berry: "Pamtre",  },
  { key: "Gastly_Bluk", pokemon: [ "Gastly", "Haunter", "Gengar",  ], default: "Gengar", berry: "Bluk",  },
  { key: "Onix_Sitrus", pokemon: [ "Onix",  ], default: "Onix", berry: "Sitrus",  },
  { key: "Onix_Belue", pokemon: [ "Steelix",  ], default: "Steelix", berry: "Belue",  },
  { key: "Cubone_Figy", pokemon: [ "Cubone", "Marowak",  ], default: "Marowak", berry: "Figy",  },
  { key: "Kangaskhan_Persim", pokemon: [ "Kangaskhan",  ], default: "Kangaskhan", berry: "Persim",  },
  { key: "Mime Jr._Mago", pokemon: [ "Mime Jr.", "Mr. Mime",  ], default: "Mr. Mime", berry: "Mago",  },
  { key: "Pinsir_Lum", pokemon: [ "Pinsir",  ], default: "Pinsir", berry: "Lum",  },
  { key: "Ditto_Persim", pokemon: [ "Ditto",  ], default: "Ditto", berry: "Persim",  },
  { key: "Eevee_Persim", pokemon: [ "Eevee",  ], default: "Eevee", berry: "Persim",  },
  { key: "Eevee_Oran", pokemon: [ "Vaporeon",  ], default: "Vaporeon", berry: "Oran",  },
  { key: "Eevee_Grepa", pokemon: [ "Jolteon",  ], default: "Jolteon", berry: "Grepa",  },
  { key: "Eevee_Leppa", pokemon: [ "Flareon",  ], default: "Flareon", berry: "Leppa",  },
  { key: "Eevee_Mago", pokemon: [ "Espeon",  ], default: "Espeon", berry: "Mago",  },
  { key: "Eevee_Wiki", pokemon: [ "Umbreon",  ], default: "Umbreon", berry: "Wiki",  },
  { key: "Eevee_Durin", pokemon: [ "Leafeon",  ], default: "Leafeon", berry: "Durin",  },
  { key: "Eevee_Rawst", pokemon: [ "Glaceon",  ], default: "Glaceon", berry: "Rawst",  },
  { key: "Eevee_Pecha", pokemon: [ "Sylveon",  ], default: "Sylveon", berry: "Pecha",  },
  { key: "Dratini_Yache", pokemon: [ "Dratini", "Dragonair", "Dragonite",  ], default: "Dragonite", berry: "Yache",  },
  { key: "Chikorita_Durin", pokemon: [ "Chikorita", "Bayleef", "Meganium",  ], default: "Meganium", berry: "Durin",  },
  { key: "Cyndaquil_Leppa", pokemon: [ "Cyndaquil", "Quilava", "Typhlosion",  ], default: "Typhlosion", berry: "Leppa",  },
  { key: "Totodile_Oran", pokemon: [ "Totodile", "Croconaw", "Feraligatr",  ], default: "Feraligatr", berry: "Oran",  },
  { key: "Togepi_Pecha", pokemon: [ "Togepi", "Togetic", "Togekiss",  ], default: "Togekiss", berry: "Pecha",  },
  { key: "Mareep_Grepa", pokemon: [ "Mareep", "Flaaffy", "Ampharos",  ], default: "Ampharos", berry: "Grepa",  },
  { key: "Bonsly_Sitrus", pokemon: [ "Bonsly", "Sudowoodo",  ], default: "Sudowoodo", berry: "Sitrus",  },
  { key: "Wooper_Oran", pokemon: [ "Wooper", "Quagsire",  ], default: "Quagsire", berry: "Oran",  },
  { key: "Wynaut_Mago", pokemon: [ "Wynaut", "Wobbuffet",  ], default: "Wobbuffet", berry: "Mago",  },
  { key: "Heracross_Lum", pokemon: [ "Heracross",  ], default: "Heracross", berry: "Lum",  },
  { key: "Delibird_Pamtre", pokemon: [ "Delibird",  ], default: "Delibird", berry: "Pamtre",  },
  { key: "Houndour_Wiki", pokemon: [ "Houndour", "Houndoom",  ], default: "Houndoom", berry: "Wiki",  },
  { key: "Raiku_Grepa", pokemon: [ "Raiku",  ], default: "Raiku", berry: "Grepa",  },
  { key: "Entei_Leppa", pokemon: [ "Entei",  ], default: "Entei", berry: "Leppa",  },
  { key: "Suicune_Oran", pokemon: [ "Suicune",  ], default: "Suicune", berry: "Oran",  },
  { key: "Larvitar_Sitrus", pokemon: [ "Larvitar", "Pupitar",  ], default: "Larvitar", berry: "Sitrus",  },
  { key: "Larvitar_Wiki", pokemon: [ "Tyranitar",  ], default: "Tyranitar", berry: "Wiki",  },
  { key: "Ralts_Mago", pokemon: [ "Ralts", "Kirlia", "Gardevoir",  ], default: "Gardevoir", berry: "Mago",  },
  { key: "Ralts_Cheri", pokemon: [ "Gallade",  ], default: "Gallade", berry: "Cheri",  },
  { key: "Slakoth_Persim", pokemon: [ "Slakoth", "Vigoroth", "Slaking",  ], default: "Slaking", berry: "Persim",  },
  { key: "Aron_Belue", pokemon: [ "Aron", "Lairon", "Aggron",  ], default: "Aggron", berry: "Belue",  },
  { key: "Sableye_Wiki", pokemon: [ "Sableye",  ], default: "Sableye", berry: "Wiki",  },
  { key: "Gulpin_Chesto", pokemon: [ "Gulpin", "Swalot",  ], default: "Swalot", berry: "Chesto",  },
  { key: "Swablu_Pamtre", pokemon: [ "Swablu",  ], default: "Swablu", berry: "Pamtre",  },
  { key: "Swablu_Yache", pokemon: [ "Altaria",  ], default: "Altaria", berry: "Yache",  },
  { key: "Shuppet_Bluk", pokemon: [ "Shuppet", "Banette",  ], default: "Banette", berry: "Bluk",  },
  { key: "Absol_Wiki", pokemon: [ "Absol",  ], default: "Absol", berry: "Wiki",  },
  { key: "Spheal_Rawst", pokemon: [ "Spheal", "Sealeo", "Walrein",  ], default: "Walrein", berry: "Rawst",  },
  { key: "Shinx_Grepa", pokemon: [ "Shinx", "Luxio", "Luxray",  ], default: "Luxray", berry: "Grepa",  },
  { key: "Drifloon_Bluk", pokemon: [ "Drifloon", "Drifblim",  ], default: "Drifblim", berry: "Bluk",  },
  { key: "Riolu_Cheri", pokemon: [ "Riolu", "Lucario",  ], default: "Lucario", berry: "Cheri",  },
  { key: "Croagunk_Chesto", pokemon: [ "Croagunk", "Toxicroak",  ], default: "Toxicroak", berry: "Chesto",  },
  { key: "Snover_Rawst", pokemon: [ "Snover", "Abomasnow",  ], default: "Abomasnow", berry: "Rawst",  },
  { key: "Rufflet_Pamtre", pokemon: [ "Rufflet", "Braviary",  ], default: "Braviary", berry: "Pamtre",  },
  { key: "Dedenne_Grepa", pokemon: [ "Dedenne",  ], default: "Dedenne", berry: "Grepa",  },
  { key: "Grubbin_Lum", pokemon: [ "Grubbin", "Charjabug", "Vikabolt",  ], default: "Vikabolt", berry: "Lum",  },
  { key: "Stufful_Cheri", pokemon: [ "Stufful", "Bewear",  ], default: "Bewear", berry: "Cheri",  },
  { key: "Comfey_Pecha", pokemon: [ "Comfey",  ], default: "Comfey", berry: "Pecha",  },
  { key: "Mimikyu_Bluk", pokemon: [ "Mimikyu",  ], default: "Mimikyu", berry: "Bluk",  },
  { key: "Cramorant_Pamtre", pokemon: [ "Cramorant",  ], default: "Cramorant", berry: "Pamtre",  },
  { key: "Sprigatito_Durin", pokemon: [ "Sprigatito", "Floragato",  ], default: "Sprigatito", berry: "Durin",  },
  { key: "Sprigatito_Wiki", pokemon: [ "Meowscarada",  ], default: "Meowscarada", berry: "Wiki",  },
  { key: "Fuecoco_Leppa", pokemon: [ "Fuecoco", "Crocalor",  ], default: "Fuecoco", berry: "Leppa",  },
  { key: "Fuecoco_Bluk", pokemon: [ "Skeledirge",  ], default: "Skeledirge", berry: "Bluk",  },
  { key: "Quaxly_Oran", pokemon: [ "Quaxly", "Quaxwell",  ], default: "Quaxly", berry: "Oran",  },
  { key: "Quaxly_Cheri", pokemon: [ "Quaquaval",  ], default: "Quaquaval", berry: "Cheri",  },
]
