
export type Pokemon = {
  dexNumber: string,
  originalDexNumber?: string, // If the dex number is modified to be unique (i.e. Alolan Vulpix)
  name: string,
  berry: string,
  ingredient_1: string,
  ingredient_2: string,
  ingredient_3: string,
  Perf?: boolean,
  ingredientLevel30?: boolean,
  ingredientLevel60?: boolean,
  ingredientLevel30Override?: string,
  ingredientLevel60Override?: string,
}

export const savedPokedex : Pokemon[] = [
  { dexNumber: "1", name: "Bulbasaur", berry: "Durin", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Potato",  },
  { dexNumber: "2", name: "Ivysaur", berry: "Durin", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Potato",  },
  { dexNumber: "3", name: "Venusaur", berry: "Durin", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Potato",  },
  { dexNumber: "4", name: "Charmander", berry: "Leppa", ingredient_1: "Sausage", ingredient_2: "Ginger", ingredient_3: "Herb",  },
  { dexNumber: "5", name: "Charmeleon", berry: "Leppa", ingredient_1: "Sausage", ingredient_2: "Ginger", ingredient_3: "Herb",  },
  { dexNumber: "6", name: "Charizard", berry: "Leppa", ingredient_1: "Sausage", ingredient_2: "Ginger", ingredient_3: "Herb",  },
  { dexNumber: "7", name: "Squirtle", berry: "Oran", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "8", name: "Wartortle", berry: "Oran", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "9", name: "Blastoise", berry: "Oran", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "10", name: "Caterpie", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Soybean",  },
  { dexNumber: "11", name: "Metapod", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Soybean",  },
  { dexNumber: "12", name: "Butterfree", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Tomato", ingredient_3: "Soybean",  },
  { dexNumber: "19", name: "Rattata", berry: "Persim", ingredient_1: "Apple", ingredient_2: "Soybean", ingredient_3: "Sausage",  },
  { dexNumber: "20", name: "Raticate", berry: "Persim", ingredient_1: "Apple", ingredient_2: "Soybean", ingredient_3: "Sausage",  },
  { dexNumber: "23", name: "Ekans", berry: "Chesto", ingredient_1: "Sausage", ingredient_2: "Egg", ingredient_3: "Herb",  },
  { dexNumber: "24", name: "Arbok", berry: "Chesto", ingredient_1: "Sausage", ingredient_2: "Egg", ingredient_3: "Herb",  },
  { dexNumber: "172", name: "Pichu", berry: "Grepa", ingredient_1: "Apple", ingredient_2: "Ginger", ingredient_3: "Egg",  },
  { dexNumber: "25", name: "Pikachu", berry: "Grepa", ingredient_1: "Apple", ingredient_2: "Ginger", ingredient_3: "Egg",  },
  { dexNumber: "26", name: "Raichu", berry: "Grepa", ingredient_1: "Apple", ingredient_2: "Ginger", ingredient_3: "Egg",  },
  { dexNumber: "173", name: "Cleffa", berry: "Pecha", ingredient_1: "Apple", ingredient_2: "Honey", ingredient_3: "Soybean",  },
  { dexNumber: "35", name: "Clefairy", berry: "Pecha", ingredient_1: "Apple", ingredient_2: "Honey", ingredient_3: "Soybean",  },
  { dexNumber: "36", name: "Clefable", berry: "Pecha", ingredient_1: "Apple", ingredient_2: "Honey", ingredient_3: "Soybean",  },
  { dexNumber: "37", name: "Vulpix", berry: "Leppa", ingredient_1: "Soybean", ingredient_2: "Corn", ingredient_3: "Potato",  },
  // { dexNumber: "037-alolanvulpix", name: "Alolan Vulpix", berry: "Rawst", ingredient_1: "Soybean", ingredient_2: "Corn", ingredient_3: "Potato",  },
  { dexNumber: "38", name: "Ninetales", berry: "Leppa", ingredient_1: "Soybean", ingredient_2: "Corn", ingredient_3: "Potato",  },
  // { dexNumber: "038-alolanninetales", name: "Alolan Ninetales", berry: "Rawst", ingredient_1: "Soybean", ingredient_2: "Corn", ingredient_3: "Potato",  },
  { dexNumber: "174", name: "Igglybuff", berry: "Pecha", ingredient_1: "Honey", ingredient_2: "Oil", ingredient_3: "Cacao",  },
  { dexNumber: "39", name: "Jigglypuff", berry: "Pecha", ingredient_1: "Honey", ingredient_2: "Oil", ingredient_3: "Cacao",  },
  { dexNumber: "40", name: "Wigglytuff", berry: "Pecha", ingredient_1: "Honey", ingredient_2: "Oil", ingredient_3: "Cacao",  },
  { dexNumber: "50", name: "Diglett", berry: "Figy", ingredient_1: "Tomato", ingredient_2: "Leek", ingredient_3: "Soybean",  },
  { dexNumber: "51", name: "Dugtrio", berry: "Figy", ingredient_1: "Tomato", ingredient_2: "Leek", ingredient_3: "Soybean",  },
  { dexNumber: "52", name: "Meowth", berry: "Persim", ingredient_1: "Milk", ingredient_2: "Sausage", ingredient_3: "0",  },
  { dexNumber: "53", name: "Persian", berry: "Persim", ingredient_1: "Milk", ingredient_2: "Sausage", ingredient_3: "0",  },
  { dexNumber: "54", name: "Psyduck", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Apple", ingredient_3: "Sausage",  },
  { dexNumber: "55", name: "Golduck", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Apple", ingredient_3: "Sausage",  },
  { dexNumber: "56", name: "Mankey", berry: "Cheri", ingredient_1: "Sausage", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "57", name: "Primeape", berry: "Cheri", ingredient_1: "Sausage", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "58", name: "Growlithe", berry: "Leppa", ingredient_1: "Herb", ingredient_2: "Sausage", ingredient_3: "Milk",  },
  { dexNumber: "59", name: "Arcanine", berry: "Leppa", ingredient_1: "Herb", ingredient_2: "Sausage", ingredient_3: "Milk",  },
  { dexNumber: "69", name: "Bellsprout", berry: "Durin", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "70", name: "Weepinbell", berry: "Durin", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "71", name: "Victreebel", berry: "Durin", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "74", name: "Geodude", berry: "Sitrus", ingredient_1: "Soybean", ingredient_2: "Potato", ingredient_3: "Mushroom",  },
  { dexNumber: "75", name: "Graveler", berry: "Sitrus", ingredient_1: "Soybean", ingredient_2: "Potato", ingredient_3: "Mushroom",  },
  { dexNumber: "76", name: "Golem", berry: "Sitrus", ingredient_1: "Soybean", ingredient_2: "Potato", ingredient_3: "Mushroom",  },
  { dexNumber: "79", name: "Slowpoke", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Tail", ingredient_3: "Tomato",  },
  { dexNumber: "80", name: "Slowbro", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Tail", ingredient_3: "Tomato",  },
  { dexNumber: "199", name: "Slowking", berry: "Oran", ingredient_1: "Cacao", ingredient_2: "Tail", ingredient_3: "Tomato",  },
  { dexNumber: "81", name: "Magnemite", berry: "Belue", ingredient_1: "Oil", ingredient_2: "Herb", ingredient_3: "0",  },
  { dexNumber: "82", name: "Magneton", berry: "Belue", ingredient_1: "Oil", ingredient_2: "Herb", ingredient_3: "0",  },
  { dexNumber: "462", name: "Magnezone", berry: "Belue", ingredient_1: "Oil", ingredient_2: "Herb", ingredient_3: "0",  },
  { dexNumber: "83", name: "Farfetch'd", berry: "Pamtre", ingredient_1: "Leek", ingredient_2: "Sausage", ingredient_3: "Ginger",  },
  { dexNumber: "84", name: "Doduo", berry: "Pamtre", ingredient_1: "Soybean", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "85", name: "Dodrio", berry: "Pamtre", ingredient_1: "Soybean", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "92", name: "Gastly", berry: "Bluk", ingredient_1: "Herb", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "93", name: "Haunter", berry: "Bluk", ingredient_1: "Herb", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "94", name: "Gengar", berry: "Bluk", ingredient_1: "Herb", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "95", name: "Onix", berry: "Sitrus", ingredient_1: "Tomato", ingredient_2: "Sausage", ingredient_3: "Potato",  },
  { dexNumber: "208", name: "Steelix", berry: "Belue", ingredient_1: "Tomato", ingredient_2: "Sausage", ingredient_3: "Potato",  },
  { dexNumber: "104", name: "Cubone", berry: "Figy", ingredient_1: "Ginger", ingredient_2: "Cacao", ingredient_3: "0",  },
  { dexNumber: "105", name: "Marowak", berry: "Figy", ingredient_1: "Ginger", ingredient_2: "Cacao", ingredient_3: "0",  },
  { dexNumber: "440", name: "Happiny", berry: "Persim", ingredient_1: "Egg", ingredient_2: "Potato", ingredient_3: "Honey",  },
  { dexNumber: "113", name: "Chansey", berry: "Persim", ingredient_1: "Egg", ingredient_2: "Potato", ingredient_3: "Honey",  },
  { dexNumber: "242", name: "Blissey", berry: "Persim", ingredient_1: "Egg", ingredient_2: "Potato", ingredient_3: "Honey",  },
  { dexNumber: "115", name: "Kangaskhan", berry: "Persim", ingredient_1: "Ginger", ingredient_2: "Potato", ingredient_3: "Soybean",  },
  { dexNumber: "439", name: "Mime Jr.", berry: "Mago", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "122", name: "Mr. Mime", berry: "Mago", ingredient_1: "Tomato", ingredient_2: "Potato", ingredient_3: "Leek",  },
  { dexNumber: "127", name: "Pinsir", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Apple", ingredient_3: "Sausage",  },
  { dexNumber: "132", name: "Ditto", berry: "Persim", ingredient_1: "Oil", ingredient_2: "Leek", ingredient_3: "Tail",  },
  { dexNumber: "133", name: "Eevee", berry: "Persim", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "134", name: "Vaporeon", berry: "Oran", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "135", name: "Jolteon", berry: "Grepa", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "136", name: "Flareon", berry: "Leppa", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "196", name: "Espeon", berry: "Mago", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "197", name: "Umbreon", berry: "Wiki", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "470", name: "Leafeon", berry: "Durin", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "471", name: "Glaceon", berry: "Rawst", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "700", name: "Sylveon", berry: "Pecha", ingredient_1: "Milk", ingredient_2: "Cacao", ingredient_3: "Sausage",  },
  { dexNumber: "147", name: "Dratini", berry: "Yache", ingredient_1: "Herb", ingredient_2: "Corn", ingredient_3: "Oil",  },
  { dexNumber: "148", name: "Dragonair", berry: "Yache", ingredient_1: "Herb", ingredient_2: "Corn", ingredient_3: "Oil",  },
  { dexNumber: "149", name: "Dragonite", berry: "Yache", ingredient_1: "Herb", ingredient_2: "Corn", ingredient_3: "Oil",  },
  { dexNumber: "152", name: "Chikorita", berry: "Durin", ingredient_1: "Cacao", ingredient_2: "Honey", ingredient_3: "Leek",  },
  { dexNumber: "153", name: "Bayleef", berry: "Durin", ingredient_1: "Cacao", ingredient_2: "Honey", ingredient_3: "Leek",  },
  { dexNumber: "154", name: "Meganium", berry: "Durin", ingredient_1: "Cacao", ingredient_2: "Honey", ingredient_3: "Leek",  },
  { dexNumber: "155", name: "Cyndaquil", berry: "Leppa", ingredient_1: "Ginger", ingredient_2: "Herb", ingredient_3: "Oil",  },
  { dexNumber: "156", name: "Quilava", berry: "Leppa", ingredient_1: "Ginger", ingredient_2: "Herb", ingredient_3: "Oil",  },
  { dexNumber: "157", name: "Typhlosion", berry: "Leppa", ingredient_1: "Ginger", ingredient_2: "Herb", ingredient_3: "Oil",  },
  { dexNumber: "158", name: "Totodile", berry: "Oran", ingredient_1: "Sausage", ingredient_2: "Oil", ingredient_3: "0",  },
  { dexNumber: "159", name: "Croconaw", berry: "Oran", ingredient_1: "Sausage", ingredient_2: "Oil", ingredient_3: "0",  },
  { dexNumber: "160", name: "Feraligatr", berry: "Oran", ingredient_1: "Sausage", ingredient_2: "Oil", ingredient_3: "0",  },
  { dexNumber: "175", name: "Togepi", berry: "Pecha", ingredient_1: "Egg", ingredient_2: "Ginger", ingredient_3: "Cacao",  },
  { dexNumber: "176", name: "Togetic", berry: "Pecha", ingredient_1: "Egg", ingredient_2: "Ginger", ingredient_3: "Cacao",  },
  { dexNumber: "468", name: "Togekiss", berry: "Pecha", ingredient_1: "Egg", ingredient_2: "Ginger", ingredient_3: "Cacao",  },
  { dexNumber: "179", name: "Mareep", berry: "Grepa", ingredient_1: "Herb", ingredient_2: "Egg", ingredient_3: "0",  },
  { dexNumber: "180", name: "Flaaffy", berry: "Grepa", ingredient_1: "Herb", ingredient_2: "Egg", ingredient_3: "0",  },
  { dexNumber: "181", name: "Ampharos", berry: "Grepa", ingredient_1: "Herb", ingredient_2: "Egg", ingredient_3: "0",  },
  { dexNumber: "438", name: "Bonsly", berry: "Sitrus", ingredient_1: "Tomato", ingredient_2: "Soybean", ingredient_3: "Mushroom",  },
  { dexNumber: "185", name: "Sudowoodo", berry: "Sitrus", ingredient_1: "Tomato", ingredient_2: "Soybean", ingredient_3: "Mushroom",  },
  { dexNumber: "194", name: "Wooper", berry: "Oran", ingredient_1: "Mushroom", ingredient_2: "Potato", ingredient_3: "Sausage",  },
  // { dexNumber: "194-paldeanwooper", name: "Paldean Wooper", berry: "Chesto", ingredient_1: "Cacao", ingredient_2: "Coffee", ingredient_3: "Potato",  },
  { dexNumber: "195", name: "Quagsire", berry: "Oran", ingredient_1: "Mushroom", ingredient_2: "Potato", ingredient_3: "Sausage",  },
  { dexNumber: "198", name: "Murkrow", berry: "Wiki", ingredient_1: "Coffee", ingredient_2: "Soybean", ingredient_3: "Herb",  },
  { dexNumber: "430", name: "Honchkrow", berry: "Wiki", ingredient_1: "Coffee", ingredient_2: "Soybean", ingredient_3: "Herb",  },
  { dexNumber: "360", name: "Wynaut", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "202", name: "Wobbuffet", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Mushroom", ingredient_3: "Oil",  },
  { dexNumber: "214", name: "Heracross", berry: "Lum", ingredient_1: "Honey", ingredient_2: "Mushroom", ingredient_3: "Sausage",  },
  { dexNumber: "215", name: "Sneasel", berry: "Wiki", ingredient_1: "Sausage", ingredient_2: "Egg", ingredient_3: "Soybean",  },
  { dexNumber: "461", name: "Weavile", berry: "Wiki", ingredient_1: "Sausage", ingredient_2: "Egg", ingredient_3: "Soybean",  },
  { dexNumber: "225", name: "Delibird", berry: "Pamtre", ingredient_1: "Egg", ingredient_2: "Apple", ingredient_3: "Cacao",  },
  { dexNumber: "228", name: "Houndour", berry: "Wiki", ingredient_1: "Herb", ingredient_2: "Ginger", ingredient_3: "Leek",  },
  { dexNumber: "229", name: "Houndoom", berry: "Wiki", ingredient_1: "Herb", ingredient_2: "Ginger", ingredient_3: "Leek",  },
  { dexNumber: "243", name: "Raikou", berry: "Grepa", ingredient_1: "Sausage", ingredient_2: "Herb", ingredient_3: "Leek",  },
  { dexNumber: "244", name: "Entei", berry: "Leppa", ingredient_1: "Oil", ingredient_2: "Tomato", ingredient_3: "Mushroom",  },
  { dexNumber: "245", name: "Suicune", berry: "Oran", ingredient_1: "Apple", ingredient_2: "Oil", ingredient_3: "Corn",  },
  { dexNumber: "246", name: "Larvitar", berry: "Sitrus", ingredient_1: "Ginger", ingredient_2: "Soybean", ingredient_3: "Sausage",  },
  { dexNumber: "247", name: "Pupitar", berry: "Sitrus", ingredient_1: "Ginger", ingredient_2: "Soybean", ingredient_3: "Sausage",  },
  { dexNumber: "248", name: "Tyranitar", berry: "Wiki", ingredient_1: "Ginger", ingredient_2: "Soybean", ingredient_3: "Sausage",  },
  { dexNumber: "252", name: "Treecko", berry: "Durin", ingredient_1: "Egg", ingredient_2: "Coffee", ingredient_3: "Leek",  },
  { dexNumber: "253", name: "Grovyle", berry: "Durin", ingredient_1: "Egg", ingredient_2: "Coffee", ingredient_3: "Leek",  },
  { dexNumber: "254", name: "Sceptile", berry: "Durin", ingredient_1: "Egg", ingredient_2: "Coffee", ingredient_3: "Leek",  },
  { dexNumber: "255", name: "Torchic", berry: "Leppa", ingredient_1: "Mushroom", ingredient_2: "Soybean", ingredient_3: "Oil",  },
  { dexNumber: "256", name: "Combusken", berry: "Leppa", ingredient_1: "Mushroom", ingredient_2: "Soybean", ingredient_3: "Oil",  },
  { dexNumber: "257", name: "Blaziken", berry: "Leppa", ingredient_1: "Mushroom", ingredient_2: "Soybean", ingredient_3: "Oil",  },
  { dexNumber: "258", name: "Mudkip", berry: "Oran", ingredient_1: "Corn", ingredient_2: "Milk", ingredient_3: "Mushroom",  },
  { dexNumber: "259", name: "Marshtomp", berry: "Oran", ingredient_1: "Corn", ingredient_2: "Milk", ingredient_3: "Mushroom",  },
  { dexNumber: "260", name: "Swampert", berry: "Oran", ingredient_1: "Corn", ingredient_2: "Milk", ingredient_3: "Mushroom",  },
  { dexNumber: "280", name: "Ralts", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Corn", ingredient_3: "Leek",  },
  { dexNumber: "281", name: "Kirlia", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Corn", ingredient_3: "Leek",  },
  { dexNumber: "282", name: "Gardevoir", berry: "Mago", ingredient_1: "Apple", ingredient_2: "Corn", ingredient_3: "Leek",  },
  { dexNumber: "475", name: "Gallade", berry: "Cheri", ingredient_1: "Apple", ingredient_2: "Corn", ingredient_3: "Leek",  },
  { dexNumber: "287", name: "Slakoth", berry: "Persim", ingredient_1: "Tomato", ingredient_2: "Honey", ingredient_3: "Apple",  },
  { dexNumber: "288", name: "Vigoroth", berry: "Persim", ingredient_1: "Tomato", ingredient_2: "Honey", ingredient_3: "Apple",  },
  { dexNumber: "289", name: "Slaking", berry: "Persim", ingredient_1: "Tomato", ingredient_2: "Honey", ingredient_3: "Apple",  },
  { dexNumber: "303", name: "Mawile", berry: "Belue", ingredient_1: "Oil", ingredient_2: "Corn", ingredient_3: "Tomato",  },
  { dexNumber: "304", name: "Aron", berry: "Belue", ingredient_1: "Sausage", ingredient_2: "Coffee", ingredient_3: "Soybean",  },
  { dexNumber: "305", name: "Lairon", berry: "Belue", ingredient_1: "Sausage", ingredient_2: "Coffee", ingredient_3: "Soybean",  },
  { dexNumber: "306", name: "Aggron", berry: "Belue", ingredient_1: "Sausage", ingredient_2: "Coffee", ingredient_3: "Soybean",  },
  { dexNumber: "302", name: "Sableye", berry: "Wiki", ingredient_1: "Oil", ingredient_2: "Mushroom", ingredient_3: "Cacao",  },
  { dexNumber: "311", name: "Plusle", berry: "Grepa", ingredient_1: "Coffee", ingredient_2: "Leek", ingredient_3: "Milk",  },
  { dexNumber: "312", name: "Minun", berry: "Grepa", ingredient_1: "Honey", ingredient_2: "Egg", ingredient_3: "Milk",  },
  { dexNumber: "316", name: "Gulpin", berry: "Chesto", ingredient_1: "Soybean", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "317", name: "Swalot", berry: "Chesto", ingredient_1: "Soybean", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "333", name: "Swablu", berry: "Pamtre", ingredient_1: "Egg", ingredient_2: "Soybean", ingredient_3: "Apple",  },
  { dexNumber: "334", name: "Altaria", berry: "Yache", ingredient_1: "Egg", ingredient_2: "Soybean", ingredient_3: "Apple",  },
  { dexNumber: "353", name: "Shuppet", berry: "Bluk", ingredient_1: "Oil", ingredient_2: "Ginger", ingredient_3: "Mushroom",  },
  { dexNumber: "354", name: "Banette", berry: "Bluk", ingredient_1: "Oil", ingredient_2: "Ginger", ingredient_3: "Mushroom",  },
  { dexNumber: "359", name: "Absol", berry: "Wiki", ingredient_1: "Cacao", ingredient_2: "Apple", ingredient_3: "Mushroom",  },
  { dexNumber: "363", name: "Spheal", berry: "Rawst", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "Ginger",  },
  { dexNumber: "364", name: "Sealeo", berry: "Rawst", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "Ginger",  },
  { dexNumber: "365", name: "Walrein", berry: "Rawst", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "Ginger",  },
  { dexNumber: "403", name: "Shinx", berry: "Grepa", ingredient_1: "Tomato", ingredient_2: "Oil", ingredient_3: "Coffee",  },
  { dexNumber: "404", name: "Luxio", berry: "Grepa", ingredient_1: "Tomato", ingredient_2: "Oil", ingredient_3: "Coffee",  },
  { dexNumber: "405", name: "Luxray", berry: "Grepa", ingredient_1: "Tomato", ingredient_2: "Oil", ingredient_3: "Coffee",  },
  { dexNumber: "425", name: "Drifloon", berry: "Bluk", ingredient_1: "Corn", ingredient_2: "Oil", ingredient_3: "Potato",  },
  { dexNumber: "426", name: "Drifblim", berry: "Bluk", ingredient_1: "Corn", ingredient_2: "Oil", ingredient_3: "Potato",  },
  { dexNumber: "447", name: "Riolu", berry: "Cheri", ingredient_1: "Oil", ingredient_2: "Potato", ingredient_3: "Egg",  },
  { dexNumber: "448", name: "Lucario", berry: "Cheri", ingredient_1: "Oil", ingredient_2: "Potato", ingredient_3: "Egg",  },
  { dexNumber: "453", name: "Croagunk", berry: "Chesto", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "0",  },
  { dexNumber: "454", name: "Toxicroak", berry: "Chesto", ingredient_1: "Oil", ingredient_2: "Sausage", ingredient_3: "0",  },
  { dexNumber: "459", name: "Snover", berry: "Rawst", ingredient_1: "Tomato", ingredient_2: "Egg", ingredient_3: "Mushroom",  },
  { dexNumber: "460", name: "Abomasnow", berry: "Rawst", ingredient_1: "Tomato", ingredient_2: "Egg", ingredient_3: "Mushroom",  },
  { dexNumber: "488", name: "Cresselia", berry: "Mago", ingredient_1: "Ginger", ingredient_2: "Cacao", ingredient_3: "Tomato",  },
  { dexNumber: "491", name: "Darkrai", berry: "Wiki", ingredient_1: "Sausage", ingredient_2: "Unknown", ingredient_3: "Unknown",  },
  { dexNumber: "517", name: "Munna", berry: "Mago", ingredient_1: "Milk", ingredient_2: "Honey", ingredient_3: "Coffee",  },
  { dexNumber: "518", name: "Musharna", berry: "Mago", ingredient_1: "Milk", ingredient_2: "Honey", ingredient_3: "Coffee",  },
  { dexNumber: "627", name: "Rufflet", berry: "Pamtre", ingredient_1: "Corn", ingredient_2: "Coffee", ingredient_3: "0",  },
  { dexNumber: "628", name: "Braviary", berry: "Pamtre", ingredient_1: "Corn", ingredient_2: "Coffee", ingredient_3: "0",  },
  { dexNumber: "702", name: "Dedenne", berry: "Grepa", ingredient_1: "Apple", ingredient_2: "Cacao", ingredient_3: "Corn",  },
  { dexNumber: "736", name: "Grubbin", berry: "Lum", ingredient_1: "Coffee", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "737", name: "Charjabug", berry: "Lum", ingredient_1: "Coffee", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "738", name: "Vikavolt", berry: "Lum", ingredient_1: "Coffee", ingredient_2: "Mushroom", ingredient_3: "Honey",  },
  { dexNumber: "759", name: "Stufful", berry: "Cheri", ingredient_1: "Corn", ingredient_2: "Sausage", ingredient_3: "Egg",  },
  { dexNumber: "760", name: "Bewear", berry: "Cheri", ingredient_1: "Corn", ingredient_2: "Sausage", ingredient_3: "Egg",  },
  { dexNumber: "764", name: "Comfey", berry: "Pecha", ingredient_1: "Corn", ingredient_2: "Ginger", ingredient_3: "Cacao",  },
  { dexNumber: "778", name: "Mimikyu", berry: "Bluk", ingredient_1: "Apple", ingredient_2: "Coffee", ingredient_3: "Mushroom",  },
  { dexNumber: "845", name: "Cramorant", berry: "Pamtre", ingredient_1: "Oil", ingredient_2: "Potato", ingredient_3: "Egg",  },
  { dexNumber: "906", name: "Sprigatito", berry: "Durin", ingredient_1: "Potato", ingredient_2: "Milk", ingredient_3: "Ginger",  },
  { dexNumber: "907", name: "Floragato", berry: "Durin", ingredient_1: "Potato", ingredient_2: "Milk", ingredient_3: "Ginger",  },
  { dexNumber: "908", name: "Meowscarada", berry: "Wiki", ingredient_1: "Potato", ingredient_2: "Milk", ingredient_3: "Ginger",  },
  { dexNumber: "909", name: "Fuecoco", berry: "Leppa", ingredient_1: "Apple", ingredient_2: "Sausage", ingredient_3: "Herb",  },
  { dexNumber: "910", name: "Crocalor", berry: "Leppa", ingredient_1: "Apple", ingredient_2: "Sausage", ingredient_3: "Herb",  },
  { dexNumber: "911", name: "Skeledirge", berry: "Bluk", ingredient_1: "Apple", ingredient_2: "Sausage", ingredient_3: "Herb",  },
  { dexNumber: "912", name: "Quaxly", berry: "Oran", ingredient_1: "Soybean", ingredient_2: "Leek", ingredient_3: "Oil",  },
  { dexNumber: "913", name: "Quaxwell", berry: "Oran", ingredient_1: "Soybean", ingredient_2: "Leek", ingredient_3: "Oil",  },
  { dexNumber: "914", name: "Quaquaval", berry: "Cheri", ingredient_1: "Soybean", ingredient_2: "Leek", ingredient_3: "Oil",  },
  { dexNumber: "921", name: "Pawmi", berry: "Grepa", ingredient_1: "Cacao", ingredient_2: "Milk", ingredient_3: "Egg",  },
  { dexNumber: "922", name: "Pawmo", berry: "Grepa", ingredient_1: "Cacao", ingredient_2: "Milk", ingredient_3: "Egg",  },
  { dexNumber: "923", name: "Pawmot", berry: "Grepa", ingredient_1: "Cacao", ingredient_2: "Milk", ingredient_3: "Egg",  },
  { dexNumber: "980", name: "Clodsire", berry: "Chesto", ingredient_1: "Cacao", ingredient_2: "Coffee", ingredient_3: "Potato",  },
]

export type CustomIngredientState = {
  isActive: boolean,
  pokemon?: Pokemon | undefined,
  pokemonState?: Pokemon | undefined,
  slot?: IngredientLevel | undefined
}

export enum IngredientLevel {
  Lvl0,
  Lvl30,
  Lvl60
}

export enum CacheState {
  Selected = 1, // 001
  IngLvl30 = 2, // 010
  IngLvl60 = 4, // 100
}

export type BerryTypes = {
  index: string,
  berryName: string,
  berryImageUri: string,
  typeName: string,
  typeImageUri: string,
}

export const berryTypes : BerryTypes[] = [
  // { index: '0', berryName: "-", typeName: "-", berryImageUri: "close-button.png", typeImageUri: "close-button.png" },
  { index: '1', berryName: "Persim", typeName: "Normal", berryImageUri: "./berries/persimberry.png", typeImageUri: "./types/normal.png" },
  { index: '2', berryName: "Leppa", typeName: "Fire", berryImageUri: "./berries/leppaberry.png", typeImageUri: "./types/fire.png" },
  { index: '3', berryName: "Oran", typeName: "Water", berryImageUri: "./berries/oranberry.png", typeImageUri: "./types/water.png" },
  { index: '4', berryName: "Grepa", typeName: "Electric", berryImageUri: "./berries/grepaberry.png", typeImageUri: "./types/electric.png" },
  { index: '5', berryName: "Durin", typeName: "Grass", berryImageUri: "./berries/durinberry.png", typeImageUri: "./types/grass.png" },
  { index: '6', berryName: "Rawst", typeName: "Ice", berryImageUri: "./berries/rawstberry.png", typeImageUri: "./types/ice.png" },
  { index: '7', berryName: "Cheri", typeName: "Fighting", berryImageUri: "./berries/cheriberry.png", typeImageUri: "./types/fighting.png" },
  { index: '8', berryName: "Chesto", typeName: "Poison", berryImageUri: "./berries/chestoberry.png", typeImageUri: "./types/poison.png" },
  { index: '9', berryName: "Figy", typeName: "Ground", berryImageUri: "./berries/figyberry.png", typeImageUri: "./types/ground.png" },
  { index: '10', berryName: "Pamtre", typeName: "Flying", berryImageUri: "./berries/pamtreberry.png", typeImageUri: "./types/flying.png" },
  { index: '11', berryName: "Mago", typeName: "Psychic", berryImageUri: "./berries/magoberry.png", typeImageUri: "./types/psychic.png" },
  { index: '12', berryName: "Lum", typeName: "Bug", berryImageUri: "./berries/lumberry.png", typeImageUri: "./types/bug.png" },
  { index: '13', berryName: "Sitrus", typeName: "Rock", berryImageUri: "./berries/sitrusberry.png", typeImageUri: "./types/rock.png" },
  { index: '14', berryName: "Bluk", typeName: "Ghost", berryImageUri: "./berries/blukberry.png", typeImageUri: "./types/ghost.png" },
  { index: '15', berryName: "Yache", typeName: "Dragon", berryImageUri: "./berries/yacheberry.png", typeImageUri: "./types/dragon.png" },
  { index: '16', berryName: "Wiki", typeName: "Dark", berryImageUri: "./berries/wikiberry.png", typeImageUri: "./types/dark.png" },
  { index: '17', berryName: "Belue", typeName: "Steel", berryImageUri: "./berries/belueberry.png", typeImageUri: "./types/steel.png" },
  { index: '18', berryName: "Pecha", typeName: "Fairy", berryImageUri: "./berries/pechaberry.png", typeImageUri: "./types/fairy.png" },
]

export type Recipe = {
  Type: string,
  Recipe: string,
  RecipeApiName: string,
  Apple?: string,
  Honey?: string,
  Milk?: string,
  Ginger?: string,
  Oil?: string,
  Cacao?: string,
  Egg?: string,
  Soybean?: string,
  Potato?: string,
  Tomato?: string,
  Mushroom?: string,
  Tail?: string,
  Herb?: string,
  Leek?: string,
  Corn?: string,
  Sausage?: string,
  Coffee?: string,
  Total_ingredients: string,
}

export type Recipes = {
  recipes: Recipe[],
  loaded?: boolean
}

export const enum RecipePossibility {
    Possible,
    Impossible,
    Other
}

export type Ingredients = {
  name: string,
  uri?: string | undefined,
}

export const ingredients: Ingredients[] = [
  {name: "Apple", uri: "./ingredients/fancyapple.png"},
  {name: "Honey", uri: "./ingredients/honey.png"},
  {name: "Milk", uri: "./ingredients/moomoomilk.png"},
  {name: "Ginger", uri: "./ingredients/warmingginger.png"},
  {name: "Oil", uri: "./ingredients/pureoil.png"},
  {name: "Cacao", uri: "./ingredients/soothingcacao.png"},
  {name: "Egg", uri: "./ingredients/fancyegg.png"},
  {name: "Soybean", uri: "./ingredients/greengrasssoybeans.png"},
  {name: "Potato", uri: "./ingredients/softpotato.png"},
  {name: "Tomato", uri: "./ingredients/snoozytomato.png"},
  {name: "Mushroom", uri: "./ingredients/tastymushroom.png"},
  {name: "Tail", uri: "./ingredients/slowpoketail.png"},
  {name: "Herb", uri: "./ingredients/fieryherb.png"},
  {name: "Leek", uri: "./ingredients/largeleek.png"},
  {name: "Corn", uri: "./ingredients/greengrasscorn.png"},
  {name: "Sausage", uri: "./ingredients/beansausage.png"},
  {name: "Coffee", uri: "./ingredients/rousingcoffee.png"},
]

export const recipeDisplayValues = {
  "curry": "Curries/Stews",
  "salad": "Salads",
  "dessert": "Desserts/Drinks",
}

export const recipeTypes = [
    "curry",
    "salad",
    "dessert",
]

export const savedRecipes : Recipes = {
  recipes: [
    { "Recipe": "Fancy Apple Curry", "RecipeApiName": "FANCY_APPLE_CURRY", "Type": "curry", "Total_ingredients": "7", "Apple": "7" },
    { "Recipe": "Simple Chowder", "RecipeApiName": "SIMPLE_CHOWDER", "Type": "curry", "Total_ingredients": "7", "Milk": "7" },
    { "Recipe": "Mild Honey Curry", "RecipeApiName": "MILD_HONEY_CURRY", "Type": "curry", "Total_ingredients": "7", "Honey": "7" },
    { "Recipe": "Beanburger Curry", "RecipeApiName": "BEANBURGER_CURRY", "Type": "curry", "Total_ingredients": "7", "Sausage": "7" },
    { "Recipe": "Hearty Cheeseburger Curry", "RecipeApiName": "HEARTY_CHEESEBURGER_CURRY", "Type": "curry", "Total_ingredients": "16", "Milk": "8", "Sausage": "8" },
    { "Recipe": "\"Drought\" Katsu Curry", "RecipeApiName": "DROUGHT_KATSU_CURRY", "Type": "curry", "Total_ingredients": "15", "Sausage": "10", "Oil": "5" },
    { "Recipe": "\"Solar Power\" Tomato Curry", "RecipeApiName": "SOLAR_POWER_TOMATO_CURRY", "Type": "curry", "Total_ingredients": "15", "Tomato": "10", "Herb": "5" },
    { "Recipe": "Melty Omelette Curry", "RecipeApiName": "MELTY_OMELETTE_CURRY", "Type": "curry", "Total_ingredients": "16", "Egg": "10", "Tomato": "6" },
    { "Recipe": "Soft Potato Chowder", "RecipeApiName": "SOFT_POTATO_CHOWDER", "Type": "curry", "Total_ingredients": "22", "Milk": "10", "Potato": "8", "Mushroom": "4" },
    { "Recipe": "\"Bulk Up\" Bean Curry", "RecipeApiName": "BULK_UP_BEAN_CURRY", "Type": "curry", "Total_ingredients": "26", "Soybean": "12", "Sausage": "6", "Herb": "4", "Egg": "4" },
    { "Recipe": "\"Spore\" Mushroom Curry", "RecipeApiName": "SPORE_MUSHROOM_CURRY", "Type": "curry", "Total_ingredients": "23", "Mushroom": "14", "Potato": "9" },
    { "Recipe": "\"Egg Bomb\" Curry", "RecipeApiName": "EGG_BOMB_CURRY", "Type": "curry", "Total_ingredients": "35", "Honey": "12", "Apple": "11", "Egg": "8", "Potato": "4" },
    { "Recipe": "\"Limber\" Corn Stew", "RecipeApiName": "LIMBER_CORN_STEW", "Type": "curry", "Total_ingredients": "30", "Corn": "14", "Milk": "8", "Potato": "8" },
    { "Recipe": "\"Dizzy Punch\" Spicy Curry", "RecipeApiName": "DIZZY_PUNCH_SPICY_CURRY", "Type": "curry", "Total_ingredients": "33", "Coffee": "11", "Herb": "11", "Honey": "11" },
    { "Recipe": "Spicy Leek Curry", "RecipeApiName": "SPICY_LEEK_CURRY", "Type": "curry", "Total_ingredients": "32", "Leek": "14", "Ginger": "10", "Herb": "8" },
    { "Recipe": "Ninja Curry", "RecipeApiName": "NINJA_CURRY", "Type": "curry", "Total_ingredients": "50", "Soybean": "24", "Sausage": "9", "Leek": "12", "Mushroom": "5" },
    { "Recipe": "Grilled Tail Curry", "RecipeApiName": "GRILLED_TAIL_CURRY", "Type": "curry", "Total_ingredients": "33", "Tail": "8", "Herb": "25" },
    { "Recipe": "\"Dream Eater\" Butter Curry", "RecipeApiName": "DREAM_EATER_BUTTER_CURRY", "Type": "curry", "Total_ingredients": "55", "Potato": "18", "Tomato": "15", "Cacao": "12", "Milk": "10" },
    { "Recipe": "\"Inferno\" Corn Keema Curry", "RecipeApiName": "INFERNO_CORN_KEEMA_CURRY", "Type": "curry", "Total_ingredients": "77", "Herb": "27", "Sausage": "24", "Corn": "14", "Ginger": "12" },
    { "Recipe": "\"Hidden Power\" Perk-Up Stew", "RecipeApiName": "HIDDEN_POWER_PERK_UP_STEW", "Type": "curry", "Total_ingredients": "92", "Soybean": "28", "Tomato": "25", "Mushroom": "23", "Coffee": "16" },
    { "Recipe": "\"Cut\" Sukiyaki Curry", "RecipeApiName": "CUT_SUKIYAKI_CURRY", "Type": "curry", "Total_ingredients": "101", "Leek": "27", "Sausage": "26", "Honey": "26", "Egg": "22" },
    { "Recipe": "Fancy Apple Salad", "RecipeApiName": "FANCY_APPLE_SALAD", "Type": "salad", "Total_ingredients": "8", "Apple": "8" },
    { "Recipe": "Bean Ham Salad", "RecipeApiName": "BEAN_HAM_SALAD", "Type": "salad", "Total_ingredients": "8", "Sausage": "8" },
    { "Recipe": "Snoozy Tomato Salad", "RecipeApiName": "SNOOZY_TOMATO_SALAD", "Type": "salad", "Total_ingredients": "8", "Tomato": "8" },
    { "Recipe": "\"Snow Cloak\" Caesar Salad", "RecipeApiName": "SNOW_CLOAK_CAESAR_SALAD", "Type": "salad", "Total_ingredients": "16", "Milk": "10", "Sausage": "6" },
    { "Recipe": "\"Water Veil\" Tofu Salad", "RecipeApiName": "WATER_VEIL_TOFU_SALAD", "Type": "salad", "Total_ingredients": "24", "Soybean": "15", "Tomato": "9" },
    { "Recipe": "\"Heat Wave\" Tofu Salad", "RecipeApiName": "HEAT_WAVE_TOFU_SALAD", "Type": "salad", "Total_ingredients": "16", "Soybean": "10", "Herb": "6" },
    { "Recipe": "\"Fury Attack\" Corn Salad", "RecipeApiName": "FURY_ATTACK_CORN_SALAD", "Type": "salad", "Total_ingredients": "17", "Corn": "9", "Oil": "8" },
    { "Recipe": "\"Dazzling\" Apple Cheese Salad", "RecipeApiName": "DAZZLING_APPLE_CHEESE_SALAD", "Type": "salad", "Total_ingredients": "23", "Apple": "15", "Milk": "5", "Oil": "3" },
    { "Recipe": "Moomoo Caprese Salad", "RecipeApiName": "MOOMOO_CAPRESE_SALAD", "Type": "salad", "Total_ingredients": "23", "Milk": "12", "Tomato": "6", "Oil": "5" },
    { "Recipe": "\"Immunity\" Leek Salad", "RecipeApiName": "IMMUNITY_LEEK_SALAD", "Type": "salad", "Total_ingredients": "15", "Leek": "10", "Ginger": "5" },
    { "Recipe": "\"Superpower\" Extreme Salad", "RecipeApiName": "SUPERPOWER_EXTREME_SALAD", "Type": "salad", "Total_ingredients": "23", "Sausage": "9", "Ginger": "6", "Egg": "5", "Potato": "3" },
    { "Recipe": "\"Contrary\" Chocolate Meat Salad", "RecipeApiName": "CONTRARY_CHOCOLATE_MEAT_SALAD", "Type": "salad", "Total_ingredients": "23", "Cacao": "14", "Sausage": "9" },
    { "Recipe": "\"Gluttony\" Potato Salad", "RecipeApiName": "GLUTTONY_POTATO_SALAD", "Type": "salad", "Total_ingredients": "36", "Potato": "14", "Egg": "9", "Sausage": "7", "Apple": "6" },
    { "Recipe": "\"Overheat\" Ginger Salad", "RecipeApiName": "OVERHEAT_GINGER_SALAD", "Type": "salad", "Total_ingredients": "35", "Herb": "17", "Ginger": "10", "Tomato": "8" },
    { "Recipe": "\"Spore\" Mushroom Salad", "RecipeApiName": "SPORE_MUSHROOM_SALAD", "Type": "salad", "Total_ingredients": "33", "Mushroom": "17", "Tomato": "8", "Oil": "8" },
    { "Recipe": "\"Calm Mind\" Fruit Salad", "RecipeApiName": "CALM_MIND_FRUIT_SALAD", "Type": "salad", "Total_ingredients": "49", "Apple": "21", "Honey": "16", "Corn": "12" },
    { "Recipe": "Slowpoke Tail Pepper Salad", "RecipeApiName": "SLOWPOKE_TAIL_PEPPER_SALAD", "Type": "salad", "Total_ingredients": "35", "Tail": "10", "Herb": "10", "Oil": "15" },
    { "Recipe": "\"Cross Chop\" Salad", "RecipeApiName": "CROSS_CHOP_SALAD", "Type": "salad", "Total_ingredients": "56", "Egg": "20", "Sausage": "15", "Corn": "11", "Tomato": "10" },
    { "Recipe": "Greengrass Salad", "RecipeApiName": "GREENGRASS_SALAD", "Type": "salad", "Total_ingredients": "62", "Oil": "22", "Corn": "17", "Tomato": "14", "Potato": "9" },
    { "Recipe": "Ninja Salad", "RecipeApiName": "NINJA_SALAD", "Type": "salad", "Total_ingredients": "57", "Leek": "15", "Soybean": "19", "Mushroom": "12", "Ginger": "11" },
    { "Recipe": "\"Petal Blizzard\" Layered Salad", "RecipeApiName": "PETAL_BLIZZARD_LAYERED_SALAD", "Type": "salad", "Total_ingredients": "69", "Egg": "25", "Oil": "17", "Potato": "15", "Sausage": "12" },
    { "Recipe": "\"Apple Acid\" Yogurt-Dressed Salad", "RecipeApiName": "APPLE_ACID_YOGURT_DRESSED_SALAD", "Type": "salad", "Total_ingredients": "104", "Egg": "35", "Apple": "28", "Tomato": "23", "Milk": "18" },
    { "Recipe": "\"Defiant\" Coffee-Dressed Salad", "RecipeApiName": "DEFIANT_COFFEE_DRESSED_SALAD", "Type": "salad", "Total_ingredients": "100", "Coffee": "28", "Sausage": "28", "Oil": "22", "Potato": "22" },
    { "Recipe": "Warm Moomoo Milk", "RecipeApiName": "WARM_MOOMOO_MILK", "Type": "dessert", "Total_ingredients": "7", "Milk": "7" },
    { "Recipe": "Fancy Apple Juice", "RecipeApiName": "FANCY_APPLE_JUICE", "Type": "dessert", "Total_ingredients": "8", "Apple": "8" },
    { "Recipe": "Craft Soda Pop", "RecipeApiName": "CRAFT_SODA_POP", "Type": "dessert", "Total_ingredients": "9", "Honey": "9" },
    { "Recipe": "\"Lucky Chant\" Apple Pie", "RecipeApiName": "LUCKY_CHANT_APPLE_PIE", "Type": "dessert", "Total_ingredients": "16", "Apple": "12", "Milk": "4" },
    { "Recipe": "\"Fluffy\" Sweet Potatoes", "RecipeApiName": "FLUFFY_SWEET_POTATOES", "Type": "dessert", "Total_ingredients": "14", "Potato": "9", "Milk": "5" },
    { "Recipe": "\"Ember\" Ginger Tea", "RecipeApiName": "EMBER_GINGER_TEA", "Type": "dessert", "Total_ingredients": "16", "Ginger": "9", "Apple": "7" },
    { "Recipe": "\"Cloud Nine\" Soy Cake", "RecipeApiName": "CLOUD_NINE_SOY_CAKE", "Type": "dessert", "Total_ingredients": "15", "Egg": "8", "Soybean": "7" },
    { "Recipe": "\"Stalwart\" Vegetable Juice", "RecipeApiName": "STALWART_VEGETABLE_JUICE", "Type": "dessert", "Total_ingredients": "16", "Tomato": "9", "Apple": "7" },
    { "Recipe": "Big Malasada", "RecipeApiName": "BIG_MALASADA", "Type": "dessert", "Total_ingredients": "23", "Oil": "10", "Milk": "7", "Honey": "6" },
    { "Recipe": "\"Hustle\" Protein Smoothie", "RecipeApiName": "HUSTLE_PROTEIN_SMOOTHIE", "Type": "dessert", "Total_ingredients": "23", "Soybean": "15", "Cacao": "8" },
    { "Recipe": "\"Huge Power\" Soy Donuts", "RecipeApiName": "HUGE_POWER_SOY_DONUTS", "Type": "dessert", "Total_ingredients": "35", "Oil": "12", "Soybean": "16", "Cacao": "7" },
    { "Recipe": "\"Sweet Scent\" Chocolate Cake", "RecipeApiName": "SWEET_SCENT_CHOCOLATE_CAKE", "Type": "dessert", "Total_ingredients": "24", "Honey": "9", "Cacao": "8", "Milk": "7" },
    { "Recipe": "\"Petal Dance\" Chocolate Tart", "RecipeApiName": "PETAL_DANCE_CHOCOLATE_TART", "Type": "dessert", "Total_ingredients": "22", "Apple": "11", "Cacao": "11" },
    { "Recipe": "\"Lovely Kiss\" Smoothie", "RecipeApiName": "LOVELY_KISS_SMOOTHIE", "Type": "dessert", "Total_ingredients": "35", "Apple": "11", "Milk": "9", "Honey": "7", "Cacao": "8" },
    { "Recipe": "\"Steadfast\" Ginger Cookies", "RecipeApiName": "STEADFAST_GINGER_COOKIES", "Type": "dessert", "Total_ingredients": "35", "Honey": "14", "Ginger": "12", "Cacao": "5", "Egg": "4" },
    { "Recipe": "Neroli's Restorative Tea", "RecipeApiName": "NEROLIS_RESTORATIVE_TEA", "Type": "dessert", "Total_ingredients": "35", "Ginger": "11", "Apple": "15", "Mushroom": "9" },
    { "Recipe": "\"Explosion\" Popcorn", "RecipeApiName": "EXPLOSION_POPCORN", "Type": "dessert", "Total_ingredients": "36", "Corn": "15", "Oil": "14", "Milk": "7" },
    { "Recipe": "\"Early Bird\" Coffee Jelly", "RecipeApiName": "EARLY_BIRD_COFFEE_JELLY", "Type": "dessert", "Total_ingredients": "42", "Coffee": "16", "Milk": "14", "Honey": "12" },
    { "Recipe": "\"Mold Breaker\" Corn Tiramisu", "RecipeApiName": "MOLD_BREAKER_CORN_TIRAMISU", "Type": "dessert", "Total_ingredients": "40", "Coffee": "14", "Corn": "14", "Milk": "12" },
    { "Recipe": "Jigglypuff's Fruity Flan", "RecipeApiName": "JIGGLYPUFFS_FRUITY_FLAN", "Type": "dessert", "Total_ingredients": "55", "Honey": "20", "Egg": "15", "Milk": "10", "Apple": "10" },
    { "Recipe": "\"Teatime\" Corn Scones", "RecipeApiName": "TEATIME_CORN_SCONES", "Type": "dessert", "Total_ingredients": "67", "Apple": "20", "Ginger": "20", "Corn": "18", "Milk": "9" },
    { "Recipe": "\"Flower Gift\" Macarons", "RecipeApiName": "FLOWER_GIFT_MACARONS", "Type": "dessert", "Total_ingredients": "77", "Cacao": "25", "Egg": "25", "Honey": "17", "Milk": "10" },
    { "Recipe": "\"Zing Zap\" Spiced Cola", "RecipeApiName": "ZING_ZAP_SPICED_COLA", "Type": "dessert", "Total_ingredients": "87", "Apple": "35", "Ginger": "20", "Leek": "20", "Coffee": "12" },
    { "Recipe": "Clodsire Éclair", "RecipeApiName": "CLODSIRE_ECLAIR", "Type": "dessert", "Total_ingredients": "102", "Cacao": "30", "Milk": "26", "Coffee": "24", "Honey": "22" }
  ]
}

export type TypeGroup = {
  key: string,
  ids?: string[],
  // pokemon?: string[],
  // default?: string,
  defaultId: string,
  berry: string,
}

export type TypeGroups = {
  groups: TypeGroup[],
  processedIds: string[]
  loaded?: boolean
}

const typeGroups : TypeGroup[] = [
  { "key": "1_DURIN", "ids": [ "1", "2", "3" ], "berry": "DURIN", "defaultId": "3" },
  { "key": "2_LEPPA", "ids": [ "4", "5", "6" ], "berry": "LEPPA", "defaultId": "6" },
  { "key": "3_ORAN", "ids": [ "7", "8", "9" ], "berry": "ORAN", "defaultId": "9" },
  { "key": "4_LUM", "ids": [ "10", "11", "12" ], "berry": "LUM", "defaultId": "12" },
  { "key": "7_PERSIM", "ids": [ "19", "20" ], "berry": "PERSIM", "defaultId": "20" },
  { "key": "9_CHESTO", "ids": [ "23", "24" ], "berry": "CHESTO", "defaultId": "24" },
  { "key": "10_GREPA", "ids": [ "172", "25", "26" ], "berry": "GREPA", "defaultId": "26" },
  { "key": "14_PECHA", "ids": [ "173", "35", "36" ], "berry": "PECHA", "defaultId": "36" },
  { "key": "15_LEPPA", "ids": [ "37", "38" ], "berry": "LEPPA", "defaultId": "38" },
  { "key": "15_RAWST", "ids": [ "37-alolanvulpix", "38-alolanninetales" ], "berry": "RAWST", "defaultId": "38-alolanninetales" },
  { "key": "16_PECHA", "ids": [ "174", "39", "40" ], "berry": "PECHA", "defaultId": "40" },
  { "key": "21_FIGY", "ids": [ "50", "51" ], "berry": "FIGY", "defaultId": "51" },
  { "key": "22_PERSIM", "ids": [ "52", "53" ], "berry": "PERSIM", "defaultId": "53" },
  { "key": "23_ORAN", "ids": [ "54", "55" ], "berry": "ORAN", "defaultId": "55" },
  { "key": "24_CHERI", "ids": [ "56", "57" ], "berry": "CHERI", "defaultId": "56" },
  { "key": "25_LEPPA", "ids": [ "58", "59" ], "berry": "LEPPA", "defaultId": "59" },
  { "key": "29_DURIN", "ids": [ "69", "70", "71" ], "berry": "DURIN", "defaultId": "71" },
  { "key": "31_SITRUS", "ids": [ "74", "75", "76" ], "berry": "SITRUS", "defaultId": "76" },
  { "key": "33_ORAN", "ids": [ "79", "80", "199" ], "berry": "ORAN", "defaultId": "79" },
  { "key": "34_BELUE", "ids": [ "81", "82", "462" ], "berry": "BELUE", "defaultId": "462" },
  { "key": "35_PAMTRE", "ids": [ "83" ], "berry": "PAMTRE", "defaultId": "83" },
  { "key": "36_PAMTRE", "ids": [ "84", "85" ], "berry": "PAMTRE", "defaultId": "85" },
  { "key": "40_BLUK", "ids": [ "92", "93", "94" ], "berry": "BLUK", "defaultId": "94" },
  { "key": "41_SITRUS", "ids": [ "95" ], "berry": "SITRUS", "defaultId": "95" },
  { "key": "41_BELUE", "ids": [ "208" ], "berry": "BELUE", "defaultId": "208" },
  { "key": "46_FIGY", "ids": [ "104", "105" ], "berry": "FIGY", "defaultId": "105" },
  { "key": "51_PERSIM", "ids": [ "440", "113", "242" ], "berry": "PERSIM", "defaultId": "242" },
  { "key": "53_PERSIM", "ids": [ "115" ], "berry": "PERSIM", "defaultId": "115" },
  { "key": "57_MAGO", "ids": [ "439", "122" ], "berry": "MAGO", "defaultId": "439" },
  { "key": "62_LUM", "ids": [ "127" ], "berry": "LUM", "defaultId": "127" },
  { "key": "66_PERSIM", "ids": [ "132" ], "berry": "PERSIM", "defaultId": "132" },
  { "key": "67_PERSIM", "ids": [ "133" ], "berry": "PERSIM", "defaultId": "133" },
  { "key": "67_ORAN", "ids": [ "134" ], "berry": "ORAN", "defaultId": "134" },
  { "key": "67_GREPA", "ids": [ "135" ], "berry": "GREPA", "defaultId": "135" },
  { "key": "67_LEPPA", "ids": [ "136" ], "berry": "LEPPA", "defaultId": "136" },
  { "key": "67_MAGO", "ids": [ "196" ], "berry": "MAGO", "defaultId": "196" },
  { "key": "67_WIKI", "ids": [ "197" ], "berry": "WIKI", "defaultId": "197" },
  { "key": "67_DURIN", "ids": [ "470" ], "berry": "DURIN", "defaultId": "470" },
  { "key": "67_RAWST", "ids": [ "471" ], "berry": "RAWST", "defaultId": "471" },
  { "key": "67_PECHA", "ids": [ "700" ], "berry": "PECHA", "defaultId": "700" },
  { "key": "76_YACHE", "ids": [ "147", "148", "149" ], "berry": "YACHE", "defaultId": "149" },
  { "key": "79_DURIN", "ids": [ "152", "153", "154" ], "berry": "DURIN", "defaultId": "154" },
  { "key": "80_LEPPA", "ids": [ "155", "156", "157" ], "berry": "LEPPA", "defaultId": "157" },
  { "key": "81_ORAN", "ids": [ "158", "159", "160" ], "berry": "ORAN", "defaultId": "160" },
  { "key": "87_PECHA", "ids": [ "175", "176", "468" ], "berry": "PECHA", "defaultId": "468" },
  { "key": "89_GREPA", "ids": [ "179", "180", "181" ], "berry": "GREPA", "defaultId": "181" },
  { "key": "91_SITRUS", "ids": [ "438", "185" ], "berry": "SITRUS", "defaultId": "185" },
  { "key": "96_ORAN", "ids": [ "194", "195" ], "berry": "ORAN", "defaultId": "195" },
  { "key": "96_CHESTO", "ids": [ "194-paldeanwooper", "980" ], "berry": "CHESTO", "defaultId": "980" },
  { "key": "97_WIKI", "ids": [ "198", "430" ], "berry": "WIKI", "defaultId": "430" },
  { "key": "100_MAGO", "ids": [ "360", "202" ], "berry": "MAGO", "defaultId": "202" },
  { "key": "108_LUM", "ids": [ "214" ], "berry": "LUM", "defaultId": "214" },
  { "key": "109_WIKI", "ids": [ "215", "461" ], "berry": "WIKI", "defaultId": "461" },
  { "key": "115_PAMTRE", "ids": [ "225" ], "berry": "PAMTRE", "defaultId": "225" },
  { "key": "118_WIKI", "ids": [ "228", "229" ], "berry": "WIKI", "defaultId": "229" },
  { "key": "123_GREPA", "ids": [ "243" ], "berry": "GREPA", "defaultId": "243" },
  { "key": "124_LEPPA", "ids": [ "244" ], "berry": "LEPPA", "defaultId": "244" },
  { "key": "125_ORAN", "ids": [ "245" ], "berry": "ORAN", "defaultId": "245" },
  { "key": "126_SITRUS", "ids": [ "246", "247" ], "berry": "SITRUS", "defaultId": "246" },
  { "key": "126_WIKI", "ids": [ "248" ], "berry": "WIKI", "defaultId": "248" },
  { "key": "130_DURIN", "ids": [ "252", "253", "254" ], "berry": "DURIN", "defaultId": "254" },
  { "key": "131_LEPPA", "ids": [ "255", "256", "257" ], "berry": "LEPPA", "defaultId": "257" },
  { "key": "132_ORAN", "ids": [ "258", "259", "260" ], "berry": "ORAN", "defaultId": "260" },
  { "key": "140_MAGO", "ids": [ "280", "281", "282" ], "berry": "MAGO", "defaultId": "282" },
  { "key": "140_CHERI", "ids": [ "475" ], "berry": "CHERI", "defaultId": "475" },
  { "key": "143_PERSIM", "ids": [ "287", "288", "289" ], "berry": "PERSIM", "defaultId": "289" },
  { "key": "150_BELUE", "ids": [ "303" ], "berry": "BELUE", "defaultId": "303" },
  { "key": "151_BELUE", "ids": [ "304", "305", "306" ], "berry": "BELUE", "defaultId": "306" },
  { "key": "149_WIKI", "ids": [ "302" ], "berry": "WIKI", "defaultId": "302" },
  { "key": "154_GREPA", "ids": [ "311" ], "berry": "GREPA", "defaultId": "311" },
  { "key": "155_GREPA", "ids": [ "312" ], "berry": "GREPA", "defaultId": "312" },
  { "key": "159_CHESTO", "ids": [ "316", "317" ], "berry": "CHESTO", "defaultId": "317" },
  { "key": "168_PAMTRE", "ids": [ "333" ], "berry": "PAMTRE", "defaultId": "333" },
  { "key": "168_YACHE", "ids": [ "334" ], "berry": "YACHE", "defaultId": "334" },
  { "key": "181_BLUK", "ids": [ "353", "354" ], "berry": "BLUK", "defaultId": "354" },
  { "key": "185_WIKI", "ids": [ "359" ], "berry": "WIKI", "defaultId": "359" },
  { "key": "187_RAWST", "ids": [ "363", "364", "365" ], "berry": "RAWST", "defaultId": "365" },
  { "key": "209_GREPA", "ids": [ "403", "404", "405" ], "berry": "GREPA", "defaultId": "405" },
  { "key": "219_BLUK", "ids": [ "425", "426" ], "berry": "BLUK", "defaultId": "426" },
  { "key": "232_CHERI", "ids": [ "447", "448" ], "berry": "CHERI", "defaultId": "448" },
  { "key": "235_CHESTO", "ids": [ "453", "454" ], "berry": "CHESTO", "defaultId": "454" },
  { "key": "239_RAWST", "ids": [ "459", "460" ], "berry": "RAWST", "defaultId": "460" },
  { "key": "249_MAGO", "ids": [ "488" ], "berry": "MAGO", "defaultId": "488" },
  { "key": "252_WIKI", "ids": [ "491" ], "berry": "WIKI", "defaultId": "491" },
  { "key": "265_MAGO", "ids": [ "517", "518" ], "berry": "MAGO", "defaultId": "518" },
  { "key": "319_PAMTRE", "ids": [ "627", "628" ], "berry": "PAMTRE", "defaultId": "628" },
  { "key": "360_GREPA", "ids": [ "702" ], "berry": "GREPA", "defaultId": "702" },
  { "key": "379_LUM", "ids": [ "736", "737", "738" ], "berry": "LUM", "defaultId": "738" },
  { "key": "391_CHERI", "ids": [ "759", "760" ], "berry": "CHERI", "defaultId": "760" },
  { "key": "393_PECHA", "ids": [ "764" ], "berry": "PECHA", "defaultId": "764" },
  { "key": "404_BLUK", "ids": [ "778" ], "berry": "BLUK", "defaultId": "778" },
  { "key": "444_PAMTRE", "ids": [ "845" ], "berry": "PAMTRE", "defaultId": "845" },
  { "key": "478_DURIN", "ids": [ "906", "907" ], "berry": "DURIN", "defaultId": "906" },
  { "key": "478_WIKI", "ids": [ "908" ], "berry": "WIKI", "defaultId": "908" },
  { "key": "479_LEPPA", "ids": [ "909", "910" ], "berry": "LEPPA", "defaultId": "909" },
  { "key": "479_BLUK", "ids": [ "911" ], "berry": "BLUK", "defaultId": "911" },
  { "key": "480_ORAN", "ids": [ "912", "913" ], "berry": "ORAN", "defaultId": "912" },
  { "key": "480_CHERI", "ids": [ "914" ], "berry": "CHERI", "defaultId": "914" },
  { "key": "484_GREPA", "ids": [ "921", "922", "923" ], "berry": "GREPA", "defaultId": "923" },
  { "key": "446_CHESTO", "ids": [ "848", "849" ], "berry": "CHESTO", "defaultId": "849" }
]
  // { key: "Bulbasaur_Durin", ids: [ "1", "2", "3",  ], defaultId: "3", berry: "Durin",  },
  // { key: "Charmander_Leppa", ids: [ "4", "5", "6",  ], defaultId: "6", berry: "Leppa",  },
  // { key: "Squirtle_Oran", ids: [ "7", "8", "9",  ], defaultId: "9", berry: "Oran",  },
  // { key: "Caterpie_Lum", ids: [ "10", "11", "12",  ], defaultId: "12", berry: "Lum",  },
  // { key: "Rattata_Persim", ids: [ "19", "20",  ], defaultId: "20", berry: "Persim",  },
  // // { key: "Ekans_Chesto", pokemon: [ "Ekans", "Arbok",  ], default: "Arbok", berry: "Chesto",  },
  // // { key: "Pichu_Grepa", pokemon: [ "Pichu", "Pikachu", "Raichu",  ], default: "Raichu", berry: "Grepa",  },
  // // { key: "Cleffa_Pecha", pokemon: [ "Cleffa", "Clefairy", "Clefable",  ], default: "Clefable", berry: "Pecha",  },
  // // { key: "Vulpix_Leppa", pokemon: [ "Vulpix", "Ninetales",  ], default: "Ninetales", berry: "Leppa",  },
  // // { key: "Alolan_Vulpix_Rawst", pokemon: [ "Alolan Vulpix", "Alolan Ninetales",  ], default: "Alolan Ninetales", berry: "Rawst",  },
  // // { key: "Igglybuff_Pecha", pokemon: [ "Igglybuff", "Jigglypuff", "Wigglytuff",  ], default: "Wigglytuff", berry: "Pecha",  },
  // // { key: "Diglett_Figy", pokemon: [ "Diglett", "Dugtrio",  ], default: "Dugtrio", berry: "Figy",  },
  // // { key: "Meowth_Persim", pokemon: [ "Meowth", "Persian",  ], default: "Persian", berry: "Persim",  },
  // // { key: "Psyduck_Oran", pokemon: [ "Psyduck", "Golduck",  ], default: "Golduck", berry: "Oran",  },
  // // { key: "Mankey_Cheri", pokemon: [ "Mankey", "Primeape",  ], default: "Primeape", berry: "Cheri",  },
  // // { key: "Growlithe_Leppa", pokemon: [ "Growlithe", "Arcanine",  ], default: "Arcanine", berry: "Leppa",  },
  // // { key: "Bellsprout_Durin", pokemon: [ "Bellsprout", "Weepinbell", "Victreebel",  ], default: "Victreebel", berry: "Durin",  },
  // // { key: "Geodude_Sitrus", pokemon: [ "Geodude", "Graveler", "Golem",  ], default: "Golem", berry: "Sitrus",  },
  // // { key: "Slowpoke_Oran", pokemon: [ "Slowpoke", "Slowbro", "Slowking",  ], default: "Slowpoke", berry: "Oran",  },
  // // { key: "Magnemite_Belue", pokemon: [ "Magnemite", "Magneton", "Magnezone",  ], default: "Magnezone", berry: "Belue",  },
  // // { key: "Farfetch'd_Pamtre", pokemon: [ "Farfetch'd"  ], default: "Farfetch'd", berry: "Pamtre",  },
  // // { key: "Doduo_Pamtre", pokemon: [ "Doduo", "Dodrio",  ], default: "Dodrio", berry: "Pamtre",  },
  // // { key: "Gastly_Bluk", pokemon: [ "Gastly", "Haunter", "Gengar",  ], default: "Gengar", berry: "Bluk",  },
  // // { key: "Onix_Sitrus", pokemon: [ "Onix",  ], default: "Onix", berry: "Sitrus",  },
  // // { key: "Onix_Belue", pokemon: [ "Steelix",  ], default: "Steelix", berry: "Belue",  },
  // // { key: "Cubone_Figy", pokemon: [ "Cubone", "Marowak",  ], default: "Marowak", berry: "Figy",  },
  // // { key: "Happiny_Persim", pokemon: [ "Happiny", "Chansey", "Blissey", ], default: "Blissey", berry: "Persim",  },
  // // { key: "Kangaskhan_Persim", pokemon: [ "Kangaskhan",  ], default: "Kangaskhan", berry: "Persim",  },
  // // { key: "Mime Jr._Mago", pokemon: [ "Mime Jr.", "Mr. Mime",  ], default: "Mr. Mime", berry: "Mago",  },
  // // { key: "Pinsir_Lum", pokemon: [ "Pinsir",  ], default: "Pinsir", berry: "Lum",  },
  // // { key: "Ditto_Persim", pokemon: [ "Ditto",  ], default: "Ditto", berry: "Persim",  },
  // // { key: "Eevee_Persim", pokemon: [ "Eevee",  ], default: "Eevee", berry: "Persim",  },
  // // { key: "Eevee_Oran", pokemon: [ "Vaporeon",  ], default: "Vaporeon", berry: "Oran",  },
  // // { key: "Eevee_Grepa", pokemon: [ "Jolteon",  ], default: "Jolteon", berry: "Grepa",  },
  // // { key: "Eevee_Leppa", pokemon: [ "Flareon",  ], default: "Flareon", berry: "Leppa",  },
  // // { key: "Eevee_Mago", pokemon: [ "Espeon",  ], default: "Espeon", berry: "Mago",  },
  // // { key: "Eevee_Wiki", pokemon: [ "Umbreon",  ], default: "Umbreon", berry: "Wiki",  },
  // // { key: "Eevee_Durin", pokemon: [ "Leafeon",  ], default: "Leafeon", berry: "Durin",  },
  // // { key: "Eevee_Rawst", pokemon: [ "Glaceon",  ], default: "Glaceon", berry: "Rawst",  },
  // // { key: "Eevee_Pecha", pokemon: [ "Sylveon",  ], default: "Sylveon", berry: "Pecha",  },
  // // { key: "Dratini_Yache", pokemon: [ "Dratini", "Dragonair", "Dragonite",  ], default: "Dragonite", berry: "Yache",  },
  // // { key: "Chikorita_Durin", pokemon: [ "Chikorita", "Bayleef", "Meganium",  ], default: "Meganium", berry: "Durin",  },
  // // { key: "Cyndaquil_Leppa", pokemon: [ "Cyndaquil", "Quilava", "Typhlosion",  ], default: "Typhlosion", berry: "Leppa",  },
  // // { key: "Totodile_Oran", pokemon: [ "Totodile", "Croconaw", "Feraligatr",  ], default: "Feraligatr", berry: "Oran",  },
  // // { key: "Togepi_Pecha", pokemon: [ "Togepi", "Togetic", "Togekiss",  ], default: "Togekiss", berry: "Pecha",  },
  // // { key: "Mareep_Grepa", pokemon: [ "Mareep", "Flaaffy", "Ampharos",  ], default: "Ampharos", berry: "Grepa",  },
  // // { key: "Bonsly_Sitrus", pokemon: [ "Bonsly", "Sudowoodo",  ], default: "Sudowoodo", berry: "Sitrus",  },
  // // { key: "Wooper_Oran", pokemon: [ "Wooper", "Quagsire",  ], default: "Quagsire", berry: "Oran",  },
  // // { key: "Murkrow_Wiki", pokemon: [ "Murkrow", "Honchkrow",  ], default: "Honchkrow", berry: "Wiki",  },
  // // { key: "Paldean_Wooper_Chesto", pokemon: [ "Paldean Wooper", "Clodsire",  ], default: "Clodsire", berry: "Chesto",  },
  // // { key: "Wynaut_Mago", pokemon: [ "Wynaut", "Wobbuffet",  ], default: "Wobbuffet", berry: "Mago",  },
  // // { key: "Heracross_Lum", pokemon: [ "Heracross",  ], default: "Heracross", berry: "Lum",  },
  // // { key: "Weavile_Wiki", pokemon: [ "Sneasel", "Weavile",  ], default: "Weavile", berry: "Wiki",  },
  // // { key: "Delibird_Pamtre", pokemon: [ "Delibird",  ], default: "Delibird", berry: "Pamtre",  },
  // // { key: "Houndour_Wiki", pokemon: [ "Houndour", "Houndoom",  ], default: "Houndoom", berry: "Wiki",  },
  // // { key: "Raikou_Grepa", pokemon: [ "Raikou",  ], default: "Raikou", berry: "Grepa",  },
  // // { key: "Entei_Leppa", pokemon: [ "Entei",  ], default: "Entei", berry: "Leppa",  },
  // // { key: "Suicune_Oran", pokemon: [ "Suicune",  ], default: "Suicune", berry: "Oran",  },
  // // { key: "Larvitar_Sitrus", pokemon: [ "Larvitar", "Pupitar",  ], default: "Larvitar", berry: "Sitrus",  },
  // // { key: "Larvitar_Wiki", pokemon: [ "Tyranitar",  ], default: "Tyranitar", berry: "Wiki",  },
  // // { key: "Sceptile_Durin", pokemon: [ "Treecko", "Grovyle", "Sceptile",  ], default: "Sceptile", berry: "Durin",  },
  // // { key: "Blaziken_Leppa", pokemon: [ "Torchic", "Combusken", "Blaziken",  ], default: "Blaziken", berry: "Leppa",  },
  // // { key: "Swampert_Oran", pokemon: [ "Mudkip", "Marshtomp", "Swampert",  ], default: "Swampert", berry: "Oran",  },
  // // { key: "Ralts_Mago", pokemon: [ "Ralts", "Kirlia", "Gardevoir",  ], default: "Gardevoir", berry: "Mago",  },
  // // { key: "Ralts_Cheri", pokemon: [ "Gallade",  ], default: "Gallade", berry: "Cheri",  },
  // // { key: "Slakoth_Persim", pokemon: [ "Slakoth", "Vigoroth", "Slaking",  ], default: "Slaking", berry: "Persim",  },
  // // { key: "Mawile_Belue", pokemon: [ "Mawile",  ], default: "Mawile", berry: "Belue",  },
  // // { key: "Aron_Belue", pokemon: [ "Aron", "Lairon", "Aggron",  ], default: "Aggron", berry: "Belue",  },
  // // { key: "Sableye_Wiki", pokemon: [ "Sableye",  ], default: "Sableye", berry: "Wiki",  },
  // // { key: "Plusle_Grepa", pokemon: [ "Plusle",  ], default: "Plusle", berry: "Grepa",  },
  // // { key: "Minun_Grepa", pokemon: [ "Minun",  ], default: "Minun", berry: "Grepa",  },
  // // { key: "Gulpin_Chesto", pokemon: [ "Gulpin", "Swalot",  ], default: "Swalot", berry: "Chesto",  },
  // // { key: "Swablu_Pamtre", pokemon: [ "Swablu",  ], default: "Swablu", berry: "Pamtre",  },
  // // { key: "Swablu_Yache", pokemon: [ "Altaria",  ], default: "Altaria", berry: "Yache",  },
  // // { key: "Shuppet_Bluk", pokemon: [ "Shuppet", "Banette",  ], default: "Banette", berry: "Bluk",  },
  // // { key: "Absol_Wiki", pokemon: [ "Absol",  ], default: "Absol", berry: "Wiki",  },
  // // { key: "Spheal_Rawst", pokemon: [ "Spheal", "Sealeo", "Walrein",  ], default: "Walrein", berry: "Rawst",  },
  // // { key: "Shinx_Grepa", pokemon: [ "Shinx", "Luxio", "Luxray",  ], default: "Luxray", berry: "Grepa",  },
  // // { key: "Drifloon_Bluk", pokemon: [ "Drifloon", "Drifblim",  ], default: "Drifblim", berry: "Bluk",  },
  // // { key: "Riolu_Cheri", pokemon: [ "Riolu", "Lucario",  ], default: "Lucario", berry: "Cheri",  },
  // // { key: "Croagunk_Chesto", pokemon: [ "Croagunk", "Toxicroak",  ], default: "Toxicroak", berry: "Chesto",  },
  // // { key: "Snover_Rawst", pokemon: [ "Snover", "Abomasnow",  ], default: "Abomasnow", berry: "Rawst",  },
  // // { key: "Cresselia_Mago", pokemon: [ "Cresselia",  ], default: "Cresselia", berry: "Mago",  },
  // // { key: "Darkrai_Wiki", pokemon: [ "Darkrai",  ], default: "Darkrai", berry: "Wiki",  },
  // // { key: "Munna_Mago", pokemon: [ "Munna", "Musharna",  ], default: "Musharna", berry: "Mago",  },
  // // { key: "Rufflet_Pamtre", pokemon: [ "Rufflet", "Braviary",  ], default: "Braviary", berry: "Pamtre",  },
  // // { key: "Dedenne_Grepa", pokemon: [ "Dedenne",  ], default: "Dedenne", berry: "Grepa",  },
  // // { key: "Grubbin_Lum", pokemon: [ "Grubbin", "Charjabug", "Vikavolt",  ], default: "Vikavolt", berry: "Lum",  },
  // // { key: "Stufful_Cheri", pokemon: [ "Stufful", "Bewear",  ], default: "Bewear", berry: "Cheri",  },
  // // { key: "Comfey_Pecha", pokemon: [ "Comfey",  ], default: "Comfey", berry: "Pecha",  },
  // // { key: "Mimikyu_Bluk", pokemon: [ "Mimikyu",  ], default: "Mimikyu", berry: "Bluk",  },
  // // { key: "Cramorant_Pamtre", pokemon: [ "Cramorant",  ], default: "Cramorant", berry: "Pamtre",  },
  // // { key: "Sprigatito_Durin", pokemon: [ "Sprigatito", "Floragato",  ], default: "Sprigatito", berry: "Durin",  },
  // // { key: "Sprigatito_Wiki", pokemon: [ "Meowscarada",  ], default: "Meowscarada", berry: "Wiki",  },
  // // { key: "Fuecoco_Leppa", pokemon: [ "Fuecoco", "Crocalor",  ], default: "Fuecoco", berry: "Leppa",  },
  // // { key: "Fuecoco_Bluk", pokemon: [ "Skeledirge",  ], default: "Skeledirge", berry: "Bluk",  },
  // // { key: "Quaxly_Oran", pokemon: [ "Quaxly", "Quaxwell",  ], default: "Quaxly", berry: "Oran",  },
  // // { key: "Quaxly_Cheri", pokemon: [ "Quaquaval",  ], default: "Quaquaval", berry: "Cheri",  },
  // // { key: "Pawmi_Grepa", pokemon: [ "Pawmi", "Pawmo", "Pawmot", ], default: "Pawmot", berry: "Grepa",  },
// ]

export const savedTypeGroups: TypeGroups = {
  groups: typeGroups,
  processedIds: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "19",
    "20",
    "23",
    "24",
    "172",
    "25",
    "26",
    "173",
    "35",
    "36",
    "37",
    "38",
    "174",
    "39",
    "40",
    "50",
    "51",
    "52",
    "53",
    "863",
    "54",
    "55",
    "56",
    "57",
    "979",
    "58",
    "59",
    "69",
    "70",
    "71",
    "74",
    "75",
    "76",
    "79",
    "80",
    "199",
    "81",
    "82",
    "462",
    "83",
    "865",
    "84",
    "85",
    "92",
    "93",
    "94",
    "95",
    "208",
    "104",
    "105",
    "440",
    "113",
    "242",
    "115",
    "439",
    "122",
    "866",
    "127",
    "132",
    "133",
    "134",
    "135",
    "136",
    "196",
    "197",
    "470",
    "471",
    "700",
    "147",
    "148",
    "149",
    "152",
    "153",
    "154",
    "155",
    "156",
    "157",
    "158",
    "159",
    "160",
    "175",
    "176",
    "468",
    "179",
    "180",
    "181",
    "438",
    "185",
    "194",
    "195",
    "980",
    "198",
    "430",
    "360",
    "202",
    "214",
    "215",
    "461",
    "903",
    "225",
    "228",
    "229",
    "243",
    "244",
    "245",
    "246",
    "247",
    "248",
    "252",
    "253",
    "254",
    "255",
    "256",
    "257",
    "258",
    "259",
    "260",
    "280",
    "281",
    "282",
    "475",
    "287",
    "288",
    "289",
    "303",
    "304",
    "305",
    "306",
    "302",
    "311",
    "312",
    "316",
    "317",
    "333",
    "334",
    "353",
    "354",
    "359",
    "363",
    "364",
    "365",
    "403",
    "404",
    "405",
    "425",
    "426",
    "447",
    "448",
    "453",
    "454",
    "459",
    "460",
    "488",
    "491",
    "517",
    "518",
    "627",
    "628",
    "702",
    "736",
    "737",
    "738",
    "759",
    "760",
    "764",
    "778",
    "845",
    "906",
    "907",
    "908",
    "909",
    "910",
    "911",
    "912",
    "913",
    "914",
    "921",
    "922",
    "923",
    "848",
    "849"
  ]
}
